---
title: "STAT 245 Introduction to Statistical Methods"
engine: knitr
format: html
metadata-files:
  - ../../_website.yaml
---

## Description

This course is an introduction to basic statistical methods including frequency distributions, elementary probability, confidence intervals and tests of significance, analysis of variance, regression and correlation, contingency tables, and goodness of fit. The following is a list of demonstration html files organized by the topics.

## List of Topics

1. [Introduction of statistics and R Basics (introduction to statistics, R, import data into R)](chapter01-IntroR.html) (Chapter 1)
2. [Frequency Graph (barplot, histogram, ECDF, stem-leaf, scatterplot)](chapter02.html) (Chapter 2)
3. [Numerical Summary (mean, median, sd, quantiles, boxplot)](chapter03.spin.html) (Chapter 3)
4. Probability Theory (Chapter 4, 5, 6)
    * [Binomial Distribution](chapter05.html)
    * [Normal Distribution](chapter06.html)
5. [Sampling distribution (Central limit theory, Simulation to visualize CLT)](chapter07.html) (Chapter 7)
6. [Confidence Interval and Hypothesis Test for One-sample (z test, and t-test)](chapter08-CI-sim.html) (Chapter 8, 9)
7. [Confidence Interval and Hypothesis Test for Two-sample (z test, two-sample t-test, paired t-test)](chapter10.html) (Chapter 10)
8. [Analysis of Variance](chapter11-aov.html) (Chapter 12)
9. Chi-square test (for one or two categorical variables) (Chapter 11)
10. [Correlation and Regression (correlation, least square estimate, t-test, ANOVA, F-test for LSE)](chapter13-regression.html) (Chapter 13)

As time permits, we will additionally talk about:

11. [Regression with a Categorical Variable](chapter13-reg-cat.html) (Dummy Variable)
12. [Multiple Regression](chapter14-multireg.html) (Chapter 14)

Rmarkdown and other supporting files for producing the above html files can be found from [this Github folder](https://github.com/longhaiSK/longhaiSK.github.io/tree/main/teaching/stat245_rdemo). The chapter numbers refer to the numbers in the textbook *Introductory Statistics, 10th Edition, By Prem S. Mann*.




<footer>
Last updated on `r format(Sys.time(), "%B %d, %Y")`.
</footer>
