---
title: "STAT 345: Design and Analysis of Experiments"
engine: knitr
format: html
metadata-files:
  - ../../_website.yaml
---

## Description

An introduction to the principles of experimental design and analysis of variance based on linear models. Topics includes: randomization, blocking, factorial experiments, confounding, random effects, analysis of covariance. Emphasis will be on fundamental principles and data analysis techniques using R rather than on mathematical theory. 

## List of Topics and Materials

1. [Introduction and R Basics (introduction to statistics, R, import data into R)](introduction_short.html)
2. [Analysis of Simple Comparative Experiments](unit1.html) (paired t-test)
3. [Simple Linear Regression](unit2_regression.html)
4. [One-way ANOVA Based on Linear Models](unit2_anova.html) (Analyzing Completely Randomized Design with a Single Categorial Factor)
5. [Design and Analysis of Experiments with Block Factors](unit3.html)
6. [General Factorial Design](unit4.html)
7. [Full 2^k^ Factorial Design](unit5.html)
8. [Two-Level Fractional Factorial Design](unit7.html)
9. [Introduction Response Surface Design](unit8.html)
10. Rmarkdown and other supporting files for producing the above html files can be found from [this Github folder](https://github.com/longhaiSK/longhaiSK.github.io/tree/main/teaching/stat345). 

## Acknowledgments

Thanks to [Prof. Chunfang Devon Lin](https://sites.google.com/view/cdlin/)'s lecture notes on the same topics. Some examples are taken from the textbook [*Design and Analysis of Experiments*](https://www.wiley.com/en-br/Design+and+Analysis+of+Experiments%2C+10th+Edition-p-9781119492443) by Douglas C. Montgomery.