---
title: "[STAT 812: Computational Statistics](../stat812.html)"
subtitle: "Gibbs Sampling"
date: "September 2018"
author: "Longhai Li"
output:
  pdf_document:
    toc: yes
    fig_height: 6
    fig_width: 10
    number_sections: yes
  html_document:
       theme: united
       toc: true
       toc_float: true
       number_sections: true
       highlight: tango
       fig_width: 10
       fig_height: 8
---

# Gibbs Sampling Normal Data

## R function for Gibbs Sampling

```{r cache=TRUE}
## this function performs Gibbs sampling for normal data
## iters --- iterations of Gibbs sampling
## x --- data
## mu0 --- prior mean for mu parameter
## sigma0 -- prior variance for mu parameter
## alpha --- degree freedom for sigma parameter
## w --- prior mean for sigma parameter
gibbs_norm <- function (iters, x, mu0, sigma0, alpha, w)
{
  sumx <- sum (x)
  n <- length (x)

  ## set and initial Markov chain state
  mu <- 0
  sigma <- 1

  one_gibbs <- function ()
  {
    ## update mu
    post_var_mu <- 1 / (n/sigma + 1/sigma0)
    mu <<- rnorm (1, (sumx / sigma + mu0 / sigma0) * post_var_mu,
                 sqrt (post_var_mu))
    sigma <<- 1/rgamma (1, (alpha + n)/2, (alpha * w + sum ((x-mu)^2))/2 )
    c(mu, sigma)
  }
  mc_musigma <- replicate (iters, one_gibbs ())
  list (mu = mc_musigma[1,], sd = sqrt (mc_musigma[2,]) )
}
```

## Test 1

```{r cache=TRUE}

x <- rnorm (50)

mcsamples <- gibbs_norm (10000, x, 0, 1E10, 1E-5, 1E-5)
plot (mcsamples$mu, main = "MC trace of mu", type = "l")
plot (density (mcsamples$mu))
acf (mcsamples$mu)
quantile (mcsamples$mu, probs = c(0, 0.025, 0.5, 0.975, 1))
mean (mcsamples$mu)
sd (mcsamples$mu)
plot (mcsamples$sd, main = "MC trace of sd", type = "l")
plot (density ((mcsamples$sd)))

quantile (mcsamples$sd, probs = c(0, 0.025, 0.5, 0.975, 1))

plot (mcsamples$mu, mcsamples$sd)
```

## Test 2

```{r cache=TRUE}

x <- rnorm (50, 10, 2)

mcsamples <- gibbs_norm (10000, x, 0, 1E10, 1E-5, 1E-5)
plot (mcsamples$mu, main = "MC trace of mu", type = "l")
plot (density (mcsamples$mu))
acf (mcsamples$mu)
quantile (mcsamples$mu, probs = c(0, 0.025, 0.5, 0.975, 1))
mean (mcsamples$mu)
sd (mcsamples$mu)
plot (mcsamples$sd, main = "MC trace of sd", type = "l")
plot (density ((mcsamples$sd)))

quantile (mcsamples$sd, probs = c(0, 0.025, 0.5, 0.975, 1))

plot (mcsamples$mu, mcsamples$sd)

```

## Test 3

```{r cache=TRUE}

x <- rnorm (5000, 10, 2)


mcsamples <- gibbs_norm (10000, x, 0, 1E10, 1E-5, 1E-5)
plot (mcsamples$mu, main = "MC trace of mu", type = "l")
plot (density (mcsamples$mu))
acf (mcsamples$mu)
quantile (mcsamples$mu, probs = c(0, 0.025, 0.5, 0.975, 1))
mean (mcsamples$mu)
sd (mcsamples$mu)
plot (mcsamples$sd, main = "MC trace of sd", type = "l")
plot (density ((mcsamples$sd)))

quantile (mcsamples$sd, probs = c(0, 0.025, 0.5, 0.975, 1))

plot (mcsamples$mu, mcsamples$sd)

```

# Gibbs Sampling for Censored Normal Data

## R function for Gibbs Sampling

```{r cache=TRUE}

library (truncnorm)
## this function performs Gibbs sampling for normal data
## iters --- iterations of Gibbs sampling
## y --- data, the observed lower limits 
## l the length of interval
## mu0 --- prior mean for mu parameter
## sigma0 -- prior variance for mu parameter
## alpha --- degree freedom for sigma parameter
## w --- prior mean for sigma parameter
gibbs_norm_interval <- function (iters, y, mu0, sigma0, alpha, w, l = 1)
{
    n <- length (y)
    
    ## set and initial Markov chain state
    mu <- 0
    sigma <- 1
    x <- rep (0, n)
    one_gibbs <- function ()
    {
        for (i in 1:n)
            x[i] <<- rtruncnorm (1, a = y[i], b = y[i] + l, 
                                 mean = mu, sd = sqrt(sigma))
        sumx <- sum (x)
        ## update mu
        post_var_mu <- 1 / (n/sigma + 1/sigma0)
        post_mean_mu <- (sumx / sigma + mu0 / sigma0) * post_var_mu
        mu <<- rnorm (1,post_mean_mu, sqrt (post_var_mu))
        sigma <<- 1/rgamma (1, (alpha + n)/2, (alpha * w + sum ((x-mu)^2))/2 )
        
        
        return(c(mu, sigma, x))
    }
    mc_musigma <- replicate (iters, one_gibbs ())
    
    list (mu = mc_musigma[1,], sd = sqrt (mc_musigma[2,]), 
          x = mc_musigma[-(1:2),] )
}
```

## A Test with Normal Data Observed at Tens

```{r cache=TRUE}

x <- rnorm (200, 100, 40); 
y <- floor (x/10)*10; 

head(data.frame (x,y))

mean (y); sd (y)

mcsamples <- gibbs_norm_interval (10000, y, 0, 1E10, 1E-5, 1E-5, 10)

plot (mcsamples$mu, main = "MC trace of mu", type = "l")
plot (density (mcsamples$mu))
acf (mcsamples$mu)
quantile (mcsamples$mu, probs = c(0, 0.025, 0.5, 0.975, 1))
mean (mcsamples$mu)
sd (mcsamples$mu)
plot (mcsamples$sd, main = "MC trace of sd", type = "l")
plot (density ((mcsamples$sd)))

quantile (mcsamples$sd, probs = c(0, 0.025, 0.5, 0.975, 1))

plot (mcsamples$mu, mcsamples$sd)

plot (mcsamples$mu[1:100], mcsamples$sd[1:100], type = "b")
plot (mcsamples$x[1, 1:100], type = "l")
hist (mcsamples$x[1,])

```


