---
title: "[STAT 812: Computational Statistics](../stat812.html)"
subtitle: "Multivariate Optimization Methods for Finding MLE"
date: "Feb 2020"
author: "Longhai Li"
output:
  html_document:
       theme: united
       toc: true
       toc_float: FALSE
       number_sections: true
       highlight: tango
       fig_width: 10
       fig_height: 8
  pdf_document:
    toc: yes
    fig_height: 6
    fig_width: 10
    number_sections: yes
---


# Finding MLE for Logistic Regression with Multivariate NR Method

```{r cache=TRUE}
# function to compute logistic regression -log likelihood, -score and
# information. b=parameters, r=binary response, z=covariate
lik_score_info <- function(b,r,z) {
        u <- b[1]+b[2]*z
        u2 <- exp(u)
        l <- -sum(u*r-log(1+u2))
        p <- u2/(1+u2)
        s <- -c(sum(r-p),sum(z*(r-p)))
        v <- matrix(c(sum(p*(1-p)),sum(z*p*(1-p)),0,sum(z*z*p*(1-p))),2,2)
        v[1,2] <- v[2,1]
        list(neg.loglik=l,neg.score=s,inf=v)
}

neg_logp_logistic <- function (b, z, r)
{
    u <- b[1]+b[2]*z
    u2 <- exp(u)
    -sum(u*r-log(1+u2))
}

####### a function for finding MLE with newton method
mle_logistic_nr <- function(b0, no_iter, r, z, debug=FALSE)
{
    result_nr <- matrix(0,no_iter+1, 3)
    colnames(result_nr) <- c('beta0','beta1','neg_loglike')
    result_nr[1,] <- c(b0, 0)

    for( i in 1:no_iter + 1)
    {
         q <- lik_score_info(result_nr[i-1,1:2],r,z)
         result_nr[i,1:2] <-   result_nr[i-1,1:2] - solve(q$inf,q$neg.score)
         result_nr[i-1,3] <- q$neg.loglik
         if(debug) print(result_nr[i-1,])
    }
    result_nr[-(no_iter+1),]
}


## generate a data set

gen_logistic_data <- function(b,n)
{
    z <- sort(runif(n, -2,2))
    emu <- exp(b[1]+z*b[2])
    p <- emu/(1+emu)
    r <- (runif(n)<p)*1
    plot (z, p, type = "l",ylim=c(0,1))
    points (z, r, col = r+1)
    list(z=z,r=r)
}

data <- gen_logistic_data(c(0,1.5),200)

# using self-programmed newton method
mle_logistic_nr(c(0,3),15,data$r,data$z) 
mle_logistic_nr(c(0,5),15,data$r,data$z)

## look at contour of bivariate log likelihood

B0 <- seq (-2, 2, by = 0.1)
B1 <- seq (-10, 10, by = 0.1)
loglike_values <- matrix (0, length (B0), length (B1))
for (i in 1:length (B0)) {
    for (j in 1:length (B1))
    {
        loglike_values[i,j] <- 
            neg_logp_logistic (c(B0[i], B1[j]),z = data$z, r = data$r )
    }
}
contour (B0, B1, loglike_values, nlevels = 100)
points(mle_logistic_nr(c(0,3),15,data$r,data$z), col = 1, type = "b") 
points(mle_logistic_nr(c(0,5),15,data$r,data$z), col = 2, type = "b") 

###### Find MLE using nlm function
nlm (neg_logp_logistic, c(0,0), z = data$z, r = data$r, hessian = T) -> logit_nlm
nlm (neg_logp_logistic, c(0,5), z = data$z, r = data$r, hessian = T)
nlm (neg_logp_logistic, c(-10, -10), z = data$z, r = data$r, hessian = T)

# find MLE standard errors using hessian of negative log likelihood
sds <- sqrt (diag (solve(logit_nlm$hessian))); sds

###### find MLE using glm function

logitfit_glm <- glm (r ~ z, family = binomial(), data = data)
summary (logitfit_glm)

logitfit_glm <- glm (r ~ z, family = binomial(), data = data, start = c(0,0))
summary (logitfit_glm)

logitfit_glm <- glm (r ~ z, family = binomial(), data = data, start = c(0,2))
summary (logitfit_glm)

logitfit_glm <- glm (r ~ z, family = binomial(), data = data, start = c(0,3))
summary (logitfit_glm)

```

# Fit a non-linear model to sunspots data: using "nlm"


```{r}

#
# The model is for the data on sunspot counts supplied with R.  We
# hypothesize that the counts (actually integers, but modelled as
# non-negative continuous values) come from taking the absolute value
# of a normal variate whose mean varies with time according to a sine 
# wave.  The model parameters are a, b, f, and M, which define the
# sine wave, as M*(a+sin(b+f*t), and the log of the standard deviation
# of the observation, lsigma.
#
# We use "nlm" to find the maximum likelihood estimates

logl <- function (p, x, t)
{
    a <- p[1]
    b <- p[2]
    f <- p[3]
    M <- p[4]
    lsigma <- p[5]
    - sum(log(dnorm ( x, M*(a+sin(b+f*t)), exp (lsigma)) + 
              dnorm (-x, M*(a+sin(b+f*t)), exp (lsigma))
      )) 
}


## get the data.

x <- sunspots [1:500]
t <- 1:length(x)

# Estimation, from a carefully chosen starting point.

est <- nlm (logl, 
            p = c(a= 0, b = -1, f = 2*pi/200, M=80,lsigma = 4), 
            x = x, t = t, hessian = T)
print(est)

mle <- est$estimate
sds <- sqrt(diag(solve(est$hessian)))

# Plot the mean from the model with the MLE parameter estimates together
# with the data points.

a <- mle[1]
b <- mle[2]
f <- mle[3]
M <- mle[4]

plot(t,x,pch=20)
lines(t,abs(M*(a+sin(b+f*t))),col="red")


```

# Fit a non-linear model to sunspots data: using "nls"
```{r}
x <- sunspots [1:500]
t <- 1:length(x)
ss_data <- data.frame (sunspots = x, t = t)

nlsfit_ss <- summary (
                nls (sunspots ~ abs(M*(a+sin(b+f*t))), 
                     data = ss_data,
                     start = c(a= 0, b = -1, f = 2*pi/200, M = 80))
                )
## note that this model is different from the model given in sunspots_nlm.r

names (nlsfit_ss)

nlsfit_coef <- nlsfit_ss$coef

a2 <- nlsfit_coef[1,1]
b2 <- nlsfit_coef[2,1]
f2 <- nlsfit_coef[3,1]
M2 <- nlsfit_coef[4,1]

plot(t,x,pch=20)
lines(t,abs(M2*(a2+sin(b2+f2*t))),col="red")
```

# Other Optimization Methods

## An overview

https://scipy-lectures.org/advanced/mathematical_optimization/index.html#knowing-your-problem

## Nelder-Mead Method (A Gradient-Free Method)

https://codesachin.wordpress.com/2016/01/16/nelder-mead-optimization/

## Gradient Descent Methods (Hessian-Free Methods)

https://www.benfrederickson.com/numerical-optimization/ 
