project:
  type: website
  output-dir: .
  render:
    - "*.qmd"

website:
  title: "Professor Longhai Li"
  search:
    location: navbar
    type: overlay
  navbar:
    logo: _extensions/profweb/logo.png
    title: "Professor Longhai Li"
    background: "#c5c5c5"
    foreground: royalblue
    position: fixed-top
    collapse-below: md
    search: true
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Courses
        href: teaching.qmd
