project:
  type: default  # Stops the "Website" behavior of scanning everything
  render: 
    - publications.qmd
    # Add other files here only when you want to render them
    # - research.qmd 

format:
  html:
    toc: true
    toc-location: right
    toc-fixed: true
    toc-expand: true
    theme: none
    header-includes: |
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
      <link rel="stylesheet" href="/resources/mystyles.css">
      <link rel="stylesheet" href="/resources/iconstyles.css">
    include-in-header:
      - text: |
          <script src="/resources/mathjax.js"></script>
          <script src="/resources/rendernav.js" defer></script>