---
title: "Publications of Prof. Longhai Li"
engine: knitr
format: html
metadata-files:
  - _website.yaml
---

{{< include _ritem.qmd >}}

## Publications in Public Archives

::: {.icon-links-container style="text-align: center; font-size: 1em;"}
[<i class="ai ai-zotero"></i>](https://www.zotero.org/longhai "Zotero")
[<i class="ai ai-google-scholar"></i>](https://scholar.google.ca/citations?user=S3mYTmwAAAAJ&hl=en "Google Scholar")
[<i class="ai ai-clarivate"></i>](https://www.webofscience.com/wos/author/record/ABF-2953-2020 "Web of Science")
[<i class="ai ai-orcid"></i>](https://orcid.org/0000-0002-3074-8584 "ORCID")
[<i class="ai ai-researchgate"></i>](https://www.researchgate.net/profile/Longhai_Li5 "ResearchGate")
[<i class="ai ai-semantic-scholar"></i>](https://www.semanticscholar.org/author/Longhai-Li/33944964 "Semantic Scholar")
[<i class="ai ai-arxiv"></i>](https://arxiv.org/a/li_l_11.html "arXiv")
:::

---

## Selected Journal Articles

### Predictive Assessment of Models

`r ritem("new")`

`r ritem()` Wu, T., Feng, C., **Li, L.** (2024). Cross-validatory Z-Residual for Diagnosing Shared Frailty Models. [The American Statistician 79(2), 198–211.](https://doi.org/10.1080/00031305.2024.2421370) [[**PDF**](/doc/cv_zresidual_final.pdf)]; [[**Free Reprints**](https://www.tandfonline.com/eprint/9CQD3QCVP56MCVKFZWEY/full?target=10.1080/00031305.2024.2421370)]; [[**slides**](https://api.zotero.org/users/1693946/publications/items/7FZTDQ3Z/file/view)]; [[**Z-residual on Github**](https://tiw150.github.io/Zresidual/index.html)]; [[**Demo**](https://tiw150.github.io/CV_Zresidual_demo.html)]

`r ritem()` Wu, T., **Li, L.**, Feng, C. (2024). Z-residual diagnostic tool for assessing covariate functional form in shared frailty models. [Journal of Applied Statistics 52(1), 28–58.](https://doi.org/10.1080/02664763.2024.2355551) [[**PDF**](/doc/jas_z_residual_nolinear.pdf)]; [[**Z-residual on Github**](https://tiw150.github.io/Zresidual/index.html)]; [[**Demo**](https://tiw150.github.io/Zresidual_demo.html)] [[**slides**](https://api.zotero.org/users/1693946/publications/items/WRQUGMIR/file/view)]

`r ritem()` **Li, L.**, Wu, T., Feng, C. (2021). Model diagnostics for censored regression via randomized survival probabilities. [Statistics in Medicine 40, 1482–1497](https://doi.org/10.1002/sim.8852). [[**PDF**](/doc/1911.00198v4.pdf)]; [[**R Functions and Demonstration**](./software/NRSP)]; [[**slides**](https://api.zotero.org/users/1693946/publications/items/Z7WFLYHB/file/view)];

`r ritem()` Wu, T., Feng, C., **Li, L.** (2024). A Comparison of Estimation Methods for Shared Gamma Frailty Models. [Statistics in Biosciences 0, 1–22.](https://doi.org/10.1007/s12561-024-09444-7) [[**PDF**](/doc/sib_compfrailty.pdf)]

`r ritem()` Bai, W., Dong, M., **Li, L.**, Feng, C., Xu, W. (2021). Randomized quantile residuals for diagnosing zero-inflated generalized linear mixed models with applications to microbiome count data. [BMC Bioinformatics 22, 564.](https://doi.org/10.1186/s12859-021-04371-6) [[**slides**](/doc/talks/rqr_glmm_ssc2022.pdf)].

`r ritem()` Feng, C., **Li, L.**, Sadeghpour, A. (2020). A comparison of residual diagnosis tools for diagnosing regression models for count data. [BMC Medical Research Methodology. 20(1):175.](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-020-01055-2) [[**R code used in this paper**](https://github.com/longhaiSK/longhaiSK.github.io/tree/main/software/RQR)]

`r ritem()` **Li, L.**, Feng, C., and Qiu, S. (2017), Estimating Cross-validatory Predictive P-values with Integrated Importance Sampling for Disease Mapping Models. [Statistics in Medicine, 36(14), 220-2236](http://onlinelibrary.wiley.com/doi/10.1002/sim.7278/full). [[**PDF**](http://arxiv.org/abs/1603.07668)]; [[**slides**](/doc/talks/dmpvalues_ssc.pdf)]; [[**R Functions**](/software/dmpvalues/dmpvalues-larynx.R)].

`r ritem()` **Li, L.**, Qiu, S., Zhang, B., and Feng, C.X. (2016). Approximating Cross-validatory Predictive Evaluation in Bayesian Latent Variables Models with Integrated IS and WAIC. [Statistics and Computing, 26(4), 881-897.](http://link.springer.com/article/10.1007/s11222-015-9577-2) [[**PDF**](http://arxiv.org/abs/1404.2918)]; [[**slides**](/doc/iis/iisslides-manitoba.pdf)].

### Statistical Machine Learning

`r ritem("new")`

`r ritem()` Yin, W., **Li, L.**, Wu, F.-X. (2022). Deep learning for brain disorder diagnosis based on fMRI images. [Neurocomputing 469, 332–345.](https://doi.org/10.1016/j.neucom.2020.05.113)

`r ritem()` Dong, M., **Li, L.**, Chen, M., Kusalik, A., Xu, W. (2020). Predictive analysis methods for human microbiome data with application to Parkinson's disease. [PLOS ONE 15(8):e0237779.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0237779)

`r ritem()` Jiang, L., Greenwood, CMT, Yao, W., **Li, L.** (2020). Bayesian Hyper-LASSO Classification for Feature Selection with Application to Endometrial Cancer RNA-seq Data. [Scientific Reports 10(1):9747.](http://www.nature.com/articles/s41598-020-66466-z)

`r ritem()` Shi, J., et al. (2019). Antimicrobial resistance genetic factor identification from whole-genome sequence data using deep feature selection. [BMC Bioinformatics, 20(15):1–14](https://link-springer-com.cyber.usask.ca/article/10.1186/s12859-019-3054-4).

`r ritem()` **Li, L.** and Yao, W. (2018). Fully Bayesian Logistic Regression with Hyper-Lasso Priors for High-dimensional Feature Selection. [Journal of Statistical Computation and Simulation, 88:14, 2827-2851.](https://doi.org/10.1080/00949655.2018.1490418) [[**PDF**](http://arxiv.org/abs/1405.3319)]; [[**software**](/software/BLRHL/index.html)]; [[**slides**](/doc/bplr/bplrslides-mgill.pdf)].

`r ritem()` Yao, W. and **Li, L.** (2014). A New Regression Model: Modal Linear Regression. [Scandinavian Journal of Statistics, 41(3), 656-671](http://onlinelibrary.wiley.com/doi/10.1111/sjos.12054/abstract). [[**PDF**](/doc/others/modlin.pdf)].

`r ritem()` **Li, L.** (2012). Bias-corrected Hierarchical Bayesian Classification with a Selected Subset of High-dimensional Features. [Journal of American Statistical Association, 107:497, 120-134](http://amstat.tandfonline.com/doi/abs/10.1198/jasa.2011.ap10446). [[**PDF**](/doc/bcbcsf/jasapaper.pdf)]; [[**software**](/software/BCBCSF)]; [[**slides**](/doc/bcbcsf/shanghaistat2015_calgary_longhai_li.pdf)].

`r ritem()` **Li, L.**, and Neal, R. M. (2008). Compressing Parameters in Bayesian High-order Models with Application to Logistic Sequence Models. [Bayesian Analysis, 2008, 3(4), 793-822](http://projecteuclid.org/euclid.ba/1340370409). [[**PDF**](/doc/seqpred/seqpred.pdf)]; [[**slides**](/doc/seqpred/seqpred-ssc.pdf)]; [[**software**](/software/BPHO/release.html)].

`r ritem()` **Li, L.**, Zhang, J., and Neal, R. M. (2008). A Method for Avoiding Bias from Feature Selection with Application to Naive Bayes Classification Models. [Bayesian Analysis, 2008, 3(1), 171-196](http://projecteuclid.org/euclid.ba/1340370566). [[**PDF**](/doc/naivebayes/naivebayes.pdf)]; [[**slides**](/doc/naivebayes/uktalk.pdf)]; [[**software**](/software/predbayescor/release.html)].

### Others

`r ritem("new")`

`r ritem()` **Li, L.** (2010). Are Bayesian Inferences Weak for Wasserman's Example? [Communications in Statistics -- Computation and Simulation, 2010, 39(3), 655-667](http://www.tandfonline.com/doi/full/10.1080/03610910903576540). [[**PDF**](/doc/wman/wman-r1-online.pdf)]; [[**slides**](/doc/wman/ssc10talk.pdf)].

`r ritem()` Soltanifar, M., **Li, L.**, and Rosenthal, J. S. (2010). A Collection of Exercises in Advanced Probability Theory, World Scientific Publishing, Singapore. [[**PDF**](http://www.worldscientific.com/doi/suppl/10.1142/6300/suppl_file/6300-solutionsmanual_free.pdf)].

---

## Online Apps

`r ritem("new")`

`r ritem()` **Students' Grade Calculator:** A Shinylive app that can [calculate students' grades](./software/calcmark_shiny/) with fine-grained controls and output.
`r ritem()` **Animation of Finding $\sqrt{S}$:** [A Shinylive App for Finding Square Root using Newton Method](./software/sqrt/)
`r ritem()` **Abbreviation Extractor for Documents with Latex Equations:** A shinylive  app that can [extract abbreviations](software/abbr/extract_abbr.html) in the source text with latex equations.
`r ritem()` [Real-time estimates of the reproduction rate ($R_t$) of Canada and its provinces](./CanadaCovidRt/), a website maintained until Feb 2022.
`r ritem()` [Projections of Canada's COVID-19 Cases (up to 2020-06-30)](covid-canada.html)

---

## Software Released Publicly

`r ritem("new")`

`r ritem()`  Wu, T. and Li, L., 2026. `Zresidual`: Computing and Diagnosing Gaussian-like Residuals. \[[Github](https://tiw150.github.io/Zresidual/index.html)\]. Version 0.1-0 on Github (2026).

`r ritem()`  Li, L., 2026. R Functions for Computing Z-residuals for `survreg` and `coxph` Objects. \[[URL](https://longhaisk.github.io/software/NRSP/index.html)\].

`r ritem()`  Li, L., et al., 2021. Real-time estimates of $R_t$ for Covid-19 in Canada. \[[URL](https://longhaisk.github.io/CanadaCovidRt/)\].

`r ritem()`  Li, L. and Liu, S., 2019--2026. `HTLR`: Bayesian Logistic Regression with Hyper-LASSO priors. DOI: [10.32614/CRAN.package.HTLR](https://doi.org/10.32614/CRAN.package.HTLR). \[[CRAN](https://cran.r-project.org/web/packages/HTLR/index.html)\] \[[Github](https://longhaisk.github.io/HTLR)\] \[[URL](https://longhaisk.github.io/software/BLRHL/index.html)\]. Version 0.4 (2019), version 0.4-1 (2019), version 0.4-2 (2020), version 0.4-3 (2020), version 0.4-4 (2022), version 1.0 (2026).

`r ritem()`  Li, L., 2011--2026. `BCBCSF`: Bias-corrected Bayesian Classification with Selected Features. DOI: [10.32614/CRAN.package.BCBCSF](https://doi.org/10.32614/CRAN.package.BCBCSF). \[[CRAN](https://cran.r-project.org/web/packages/BCBCSF/index.html)\] \[[URL](https://longhaisk.github.io/software/BCBCSF/index.html)\]. Version 0.0-0 (2011), version 0.0-1 (2011), version 0.0-2 (2012), version 1.0-0 (2013), version 1.0-1 (2015), updated to version 1.0-2 (2026).

`r ritem()`  Li, L., 2018. `HTLR`: Bayesian Logistic Regression with Hyper-LASSO priors. \[[URL](https://longhaisk.github.io/software/BLRHL/index.html)\]. Pre-CRAN version (2018).

`r ritem()`  Li, L., 2016. `iIS`: R code for computing predictive p-values in disease mapping models. \[[URL](https://longhaisk.github.io/software/dmpvalues/dmpvalues-larynx.R)\].

`r ritem()`  Li, L., 2008. `gibbs.met`: Naive Gibbs Sampling with Metropolis Steps. \[[CRAN](https://cran.r-project.org/web/packages/gibbs.met/index.html)\] \[[URL](https://longhaisk.github.io/software/gibbs.met/release.html)\].

`r ritem()`  Li, L., 2008. `BPHO`: Bayesian Prediction with High-order Interactions. \[[CRAN](https://cran.r-project.org/web/packages/BPHO/index.html)\] \[[URL](https://longhaisk.github.io/software/BPHO/release.html)\].

`r ritem()`  Li, L., 2007. `predmixcor`: Classification rule based on Bayesian mixture models with feature selection bias corrected. \[[CRAN](https://cran.r-project.org/web/packages/predmixcor/index.html)\] \[[URL](https://longhaisk.github.io/software/predmixcor/release.html)\].

`r ritem()`  Li, L., 2007. `predbayescor`: Classification Rule Based on Bayesian Naive Bayes Models with Features Selection Bias Corrected. \[[CRAN](https://cran.r-project.org/web/packages/predbayescor/index.html)\] \[[URL](https://longhaisk.github.io/software/predbayescor/release.html)\].

<footer>
Last updated on `r format(Sys.time(), "%B %d, %Y")`.
</footer>