---
title: "Research Activities of Prof. Longhai Li"
engine: knitr
format: html
metadata-files:
  - _website.yaml
---


## Overview of Prof. Li's Research Activities

Prof. Li's research focuses on developing and applying statistical machine-learning methods to analyze bioinformatics and epidemiology data. His research activities are computationally intensive, aiming to develop new data analysis software and solve real problems in life and health sciences.

### Model Diagnostics and Comparison

He aims to develop new tools for evaluating Bayesian/non-Bayesian models with complex structures. Today, increasingly complicated models are being proposed for a variety of correlated data such as temporal, spatial, and repeated measurement data. There is a gap between developing new modelling methods and model validation methods. He is working on developing new residual diagnostic methods for checking the adequacy of statistical models.

### Statistical Machine Learning

He aims to develop new tools for honestly measuring the predictivity (such as error rate, AUC) of selected features, and new tools for identifying truly predictive features and for building sharper predictive models for phenotypes. He is particularly interested in uncovering the molecular mechanisms behind Alzheimer’s and Parkinson’s diseases.

## Externally Funded Research Projects

Many granting agencies including NSERC, CFI, CANSSI, CFREF, and MITACS have supported his research:

* Statistical Methodologies and Computational Tools to Identify Microbial Correlates of Canadian Bee Gut Health, [Collaborative Research Team Projects – Project 29](https://canssi.ca/story/crt-29/), Co-PI, 2025–2028.
* Geospatial Artificial Intelligence Algorithms for Automating Manual Observation Associated with Wheat Production, MITACS Accelerate Grant, PI. 2022-2025.
* Develop a web-based geospatial artificial intelligence framework to track, visualize, analyze, model, and predict infectious disease spread in real-time, MITACS Accelerate Grant, PI, 2020-2021.
* [Predictive Methods for Analyzing High-throughput and Spatial-temporal Data](https://cognit.ca/en/project/207670), NSERC Individual Discovery Grant, 2019-2024, PI.
* Genotype & Environment to Phenotype, sub-project from Canada First Research Excellence Fund (CFREF) Project "Designing Crops for Global Food Security", 2016-2019, Co-Investigator (PI: Prof. Kusalik).
* Applications of Neural Network Curve Fitting Methods for Least-squares Monte Carlo Simulations in Financial Risk Management, MITACS Accelerate Internship Fund, 2016, PI.
* [Bayesian Methods for High-dimensional and Correlated Data](https://cognit.ca/en/project/13450), NSERC Individual Discovery Grant, 2014 - 2019, PI.
* [Efficient Bayesian Analysis for Complex Models](https://www.nserc-crsng.gc.ca/ase-oro/Details-Detailles_eng.asp?id=527993), NSERC Individual Discovery Grant, 2009 - 2014, PI.
* A Computer Cluster for Research on Efficient Bayesian Statistical Methods, CFI Leaders Opportunity Fund, 2009, PI.
* Clustering Analysis for Detecting the Types of Vehicles, MITACS Accelerate Grant, 2008, Co-PI with Prof. Laverty.

<footer>
Last updated on `r format(Sys.time(), "%B %d, %Y")`.
</footer>