---
title: "Teaching Activities of Prof. Longhai Li"
engine: knitr
format: html
metadata-files:
  - _website.yaml
---

{{< include _ritem.qmd >}}

## Textbooks

`r ritem("new")` 

`r ritem()` **Theory of Statistical Inference**\
  [HTML](teaching/stat850/mathstat/index.html){.button} 
  [PDF](teaching/stat850/mathstat/mathstat-LLI.pdf){.button}
`r ritem()` **Theory of Linear Models**\
  [HTML](teaching/stat851/theorylm/index.html){.button}
  [PDF](teaching/stat851/theorylm/stat_lin_theory.pdf){.button}
`r ritem()` **Statistical Inference and Learning Methods for Research**\
  [HTML](teaching/stat845/book/index.html){.button}
  [PDF](teaching/stat845/book/stat_inference_learning.pdf){.button}

## Materials of Selected Courses

`r ritem("new")` 

`r ritem()` [STAT 245: Introduction to Statistical Methods](teaching/stat245/)
`r ritem()` [STAT 342: Mathematical Statistics](teaching/stat342/)
`r ritem()` [STAT 345/834: Design and Analysis of Experiments](teaching/stat345/)
`r ritem()` [STAT 348: Sampling Techniques](teaching/stat348/)
`r ritem()` [STAT 812/420: Computational Statistics](teaching/stat812/)
`r ritem()` [STAT 845: Statistical Methods for Research](teaching/stat845/)
`r ritem()` [STAT 850/442: Mathematical Statistics and Statistical Inference](teaching/stat850/)
`r ritem()` [STAT 851/443: Linear Statistical Models](teaching/stat851/)

## List of Taught Courses

`r ritem("new")` 

### Introductory Statistics

`r ritem()` STAT 242: [Statistical Theory and Methodology](https://catalogue.usask.ca/STAT-242)
`r ritem()` STAT 244: [Elementary Statistical Concepts](https://catalogue.usask.ca/STAT-244)
`r ritem()` STAT 245: [Introduction to Statistical Methods](https://catalogue.usask.ca/STAT-245)

### Applied Statistics

`r ritem()` STAT 345: [Design and Analysis of Experiments](https://catalogue.usask.ca/STAT-345)
`r ritem()` STAT 348: [Sampling Techniques](https://catalogue.usask.ca/STAT-348)
`r ritem()` STAT 845: [Statistical Methods for Research](https://catalogue.usask.ca/STAT-845)
`r ritem()` STAT 834: [Advanced Experimental Design](https://catalogue.usask.ca/STAT-834)
`r ritem()` STAT 848: [Multivariate Data Analysis](https://catalogue.usask.ca/STAT-848)

### Probability/Statistical Theory

`r ritem()` STAT 241: [Probability Theory](https://catalogue.usask.ca/STAT-241)
`r ritem()` STAT 342: [Probability and Mathematical Statistics](https://catalogue.usask.ca/STAT-342)
`r ritem()` STAT 442: [Statistical Inference](https://catalogue.usask.ca/STAT-442)
`r ritem()` STAT 443: [Linear Statistical Models](https://catalogue.usask.ca/STAT-443)
`r ritem()` STAT 851: [Linear Models](https://catalogue.usask.ca/STAT-851)
`r ritem()` STAT 841: [Probability Theory](https://catalogue.usask.ca/202003/STAT-841)

### Computational Statistics
`r ritem()` STAT 812: [Computational Statistics](https://catalogue.usask.ca/STAT-812)
`r ritem()` STAT 420: [Topics in Computational Statistics](https://catalogue.usask.ca/STAT-420)

## Features of Longhai Li's Teaching

His teaching is featured by incorporating cutting-edge computational/data science techniques and real-world examples into classes. 

* He introduces his students to computational tools such as R, R Markdown, python, and web-based computation for analyzing real datasets, developing statistical packages, and sharing analysis results. He has created web pages using R Markdown for all his classes on introductory and applied statistics and provided the source code for students to learn these tools. 
* He employs computational simulation and animation tools to elucidate statistical theorems and computer algorithms. 
* He is also committed to using real-world examples in his classes. For instance, he used data on [SK’s COVID-19 vaccination and hospitalization rates to demonstrate the power of Bayes' rule for understanding the efficacy of vaccination](https://longhaisk.github.io/teaching/stat342/Lec03.key.pdf#page=15). 
* He actively involves undergraduate students in his research. In 2021, he led a team supported by MITACS to develop a public website that provides [real-time reproduction rates for Canada’s national and provincial jurisdictions](./CanadaCovidRt/). He has also involved undergraduate students in building R packages (e.g. [**HTLR**](https://longhaisk.github.io/HTLR)) for statistical machine learning.

<footer>
Last updated on `r format(Sys.time(), "%B %d, %Y")`.
</footer>
