---
title: "Members of Longhai Li's Research Lab"
engine: knitr
format: html
metadata-files:
  - _website.yaml
---


## Post-doctoral Fellows

1. [Tingxuan Wu](https://tiw150.github.io), RA, Jan 2025 - Dec. 2025
2. [Tingxuan Wu](https://tiw150.github.io), PDF, co-supervised with Prof. Cindy Feng, June 2023 – April 2024
3. Ming-Ming Zhang, PDF, March 2022 - March 2025
4. [Jinhong Shi](https://www.researchgate.net/profile/Jinhong-Shi), PDF, team-supervised, 2016-2019.

## Ph.D. Students

1. Jing Wang, Ph.D in Biostatistics, Sept 2024-present, co-supervised with Prof. Li Xing

2. Tingxuan Wu, PhD in Biostatistics, 2023, co-supervised with Prof. Cindy Feng
   
   Thesis: [Residual Diagnostics and Statistical Inference for Shared Frailty Models](https://harvest.usask.ca/handle/10388/14727)
   
   Employment: Forestry Statistical Analyst, Ministry of Environment, Government of Saskatchewan
   
   Publications:
   * Wu, T., Feng, C., **Li, L.** (2024). Cross-validatory Z-Residual for Diagnosing Shared Frailty Models. [The American Statistician 79(2), 198–211.](https://doi.org/10.1080/00031305.2024.2421370) [**PDF**](/doc/cv_zresidual_final.pdf); [**Free Reprints**](https://www.tandfonline.com/eprint/9CQD3QCVP56MCVKFZWEY/full?target=10.1080/00031305.2024.2421370); [**slides**](https://api.zotero.org/users/1693946/publications/items/7FZTDQ3Z/file/view); [**Z-residual on Github**](https://github.com/tiw150/Zresidual); [**Demo**](https://tiw150.github.io/CV_Zresidual_demo.html)
   
   * Wu, T., **Li, L.**, Feng, C. (2024). Z-residual diagnostic tool for assessing covariate functional form in shared frailty models. [Journal of Applied Statistics 52(1), 28–58.](https://doi.org/10.1080/02664763.2024.2355551) [**PDF**](/doc/jas_z_residual_nolinear.pdf); [**Z-residual on Github**](https://github.com/tiw150/Zresidual); [**Demo**](https://tiw150.github.io/Zresidual_demo.html); [**slides**](https://api.zotero.org/users/1693946/publications/items/WRQUGMIR/file/view)
   
   * Wu, T., Feng, C., **Li, L.** (2024). A Comparison of Estimation Methods for Shared Gamma Frailty Models. [Statistics in Biosciences 0, 1–22.](https://doi.org/10.1007/s12561-024-09444-7) [**PDF**](/doc/sib_compfrailty.pdf)

3. Wutao Yin, Ph.D., September 2019 - December 2021, co-supervised with Prof. Fang-Xiang Wu
   
   Thesis: [Artificial Intelligence Based Methods for Autism Spectrum Disorder Diagnosis from fMRI Data](https://harvest.usask.ca/handle/10388/13732)
   
   Current position: Associate Professor, Ocean Institute, Northwestern Polytechnical University, Taicang Jiangsu, China
   
   Publications: 
   * Wutao Yin, Longhai Li, Fang-Xiang Wu, [A semi-supervised autoencoder for autism disease diagnosis, Neurocomputing, Volume 483, 2022, Pages 140-147](https://doi.org/10.1016/j.neucom.2022.02.017).   
   * Yin, W., Li, L., Wu, F.-X., 2022. [Deep learning for brain disorder diagnosis based on fMRI images. Neurocomputing 469, 332–345](https://doi.org/10.1016/j.neucom.2020.05.113). 
   * Yin, W., Li, L., Wu, F.-X., 2021. [A Graph Attention Neural Network for Diagnosing ASD with fMRI Data, in: 2021 IEEE International Conference on Bioinformatics and Biomedicine (BIBM). pp. 1131–1136.](https://doi.org/10.1109/BIBM52615.2021.9669849)

4. Lai Jiang, Ph.D., 2015
   
   Thesis: [Fully Bayesian T-probit Regression with Heavy-tailed Priors for Selection in High-Dimensional Features with Grouping Structure](/researchteam/theses/Jiang,Lai_PhD_thesis_Sep_2015.pdf) 
   
   Employment: Postdoctoral fellow at Lady Davis Institute, Jewish General Hospital, McGill University in Montreal.
   
   Publication: 
   * Jiang L, Greenwood CMT, Yao W, Li L. [Bayesian Hyper-LASSO Classification for Feature Selection with Application to Endometrial Cancer RNA-seq Data. Scientific Reports. 2020 Jun 16;10(1):9747.](http://www.nature.com/articles/s41598-020-66466-z)

## Master Students

1. Dananji Shashiprabha, M.Sc. in Statistics, Sept 2023-present, Co-supervised with Prof. Cindy Feng at U of Dalhousie.

2. Effie Wuqian Gao, M.Sc. in Biostatistics, Sept. 2022 - August 2024, Co-supervised with Prof. Cindy Feng at U of Dalhousie.
   
   Thesis: [Z-residuals for Checking Bayesian Hurdle Models](https://harvest.usask.ca/items/ea0c9479-9914-4139-8027-9145190056c6)
   
   Employment: Senior Data and Forecasting Analyst, Health Ministry, Government of Saskatchewan

3. Hao Hu, M.Sc., 2022, co-supervised with Prof. Li Xing 
   
   Thesis: [Identifying Risk Factors for Cognitive Decline Using Statistical Learning Techniques and Functional Data Analysis](https://harvest.usask.ca/bitstream/handle/10388/14244/HU-THESIS-2022.pdf?sequence=1&isAllowed=y)
   
   First Employment: Senior Statistician in Health Ministry in a Chinese goverment

4. Lina Li, M.Sc, May 2021 to September 2021, MITACS project supervisor
   
   Publication: [Real-time estimates of the reproduction rate (*R~t~*) of Canadian provinces.](./CanadaCovidRt/) 

5. Man Chen, M.Sc., 2021.
   
   Thesis: [Association between Gut Microbiome and Parkinson's Disease Revealed by Sparse Learning](https://harvest.usask.ca/bitstream/handle/10388/13403/CHEN-THESIS-2021.pdf?sequence=1&isAllowed=y).
   
   Publication: 
   * Dong M, Li L, Chen M, Kusalik A, Xu W. [Predictive analysis methods for human microbiome data with application to Parkinson's disease. PLOS ONE. 2020 Aug 24;15(8):e0237779.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0237779)
   
   First Employment: AI Engineer at [Super GeoAI Technology Inc.](https://sga.ai)

6. Mei Dong, M.Sc., 2019, co-supervised with Prof. Lloyd Balbuena
   
   Thesis: [Feature Selection Bias in Assessing the Predictivity of SNPs for Alzheimer's Disease](/researchteam/theses/DONG-THESIS-2019.pdf) 
   
   Employment: Senior Research Analyst at the University of Toronto.
   
   Publications:
   * Dong M, Li L, Chen M, Kusalik A, Xu W. [Predictive analysis methods for human microbiome data with application to Parkinson's disease. PLOS ONE. 2020 Aug 24;15(8):e0237779.](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0237779)
   * Bai, W., Dong, M., Li, L., Feng, C., Xu, W., 2021. [Randomized quantile residuals for diagnosing zero-inflated generalized linear mixed models with applications to microbiome count data. BMC Bioinformatics 22, 564.](https://doi.org/10.1186/s12859-021-04371-6)

7. Xiaoying Wang, M.Sc., 2019
   
   Thesis: [Comparison of Statistical Testing and Predictive Analysis Methods for Feature Selection in Zero-inflated Microbiome Data](/researchteam/theses/WANG-THESIS-2019.pdf) 

8. Tingxuan Wu, M.Sc. in biostatistics, 2018, co-supervised with Prof. Cindy Feng
   
   Thesis: [Randomized Survival Probability Residuals for Assessing Parametric Survival Models](/researchteam/theses/WU-THESIS-2018.pdf)
   
   Employment: PhD student at the University of Saskatchewan
   
   Publication: 
   * **Li, L.**, Wu, T., Feng, C. (2021). Model diagnostics for censored regression via randomized survival probabilities. [Statistics in Medicine 40, 1482–1497](https://doi.org/10.1002/sim.8852). [**PDF**](/doc/1911.00198v4.pdf); [**R Functions and Demonstration**](./software/NRSP); [**slides-1**](/doc/talks/slides_mdrsp.pdf); [**slides-2**](https://api.zotero.org/users/1693946/publications/items/Z7WFLYHB/file/view)

9. Wei Bai, M.Sc., 2018, co-supervised with Prof. Cindy Feng
   
   Thesis: [Randomized Quantile Residual for Assessing Generalized Linear Mixed Models with Application to Zero-Inflated Microbiome Data](/researchteam/theses/BAI-THESIS-2018.pdf)
   
   First Employment: Statistical Programmer, Everest Clinical Research, Markham, Ontario.
   
   Present Position: Lead Statistical Analyst, Bayer Pharmaceuticals, Ontario, Canada 
   
   Publication: 
   * Bai, W., Dong, M., Li, L., Feng, C., Xu, W., 2021. [Randomized quantile residuals for diagnosing zero-inflated generalized linear mixed models with applications to microbiome count data. BMC Bioinformatics 22, 564.](https://doi.org/10.1186/s12859-021-04371-6)

10. Arash Shamloo, M.MATH (project-based), 2017
    
    Project: Randomized quantile residuals for accelerated failure time models
    
    Employment: Research assistant, College of Pharmacy and Nutrition, University of Saskatchewan. 

11. Yunyang Wang, M.Sc., 2016
    
    Thesis: [Comparison of Stochastic Volatility Models Using Integrated Information Criteria](/researchteam/theses/WANG-THESIS-2016.pdf)
    
    Employments: Statistician at Montreal office of [Evidera](http://www.evidera.com/) (a PPD company), Montreal, QC
    
    First Employment: Intern at the PathWise Solutions, AON Securities, Toronto.

12. Alireza Sadeghpour, M.Sc., 2016, co-supervised with Prof. Cindy Feng
    
    Thesis: [Empirical Investigation of Randomized Quantile Residuals for Diagnosis of Non-Normal Regression Models](/researchteam/theses/alithesis.pdf)
    
    First Employment: Statistician at Health Canada, Ottawa.
    
    Publication: 
    * Feng C, Li L, Sadeghpour A. [A comparison of residual diagnosis tools for diagnosing regression models for count data. BMC Medical Research Methodology. 2020 Jul 1;20(1):175.](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-020-01055-2) 

13. Naorin Islam, M.Sc., 2016, co-supervised wtih Prof. Khan
    
    Thesis: [Substance Abuse and Health: A Structural Equation Modeling Approach to Assess Latent Health Effects](/researchteam/theses/ISLAM-THESIS-2016.pdf)
    
    First Employment: Research assistant, College of Pharmacy and Nutrition, University of Saskatchewan.

14. Shi Qiu, M.Sc., 2015 (co-supervised with Cindy X. Feng)
    
    Thesis: [Cross-validatory Model Comparison and Divergent Regions Detection using iIS and iWAIC for Disease Mapping](/researchteam/theses/QIU-THESIS.pdf)  
    
    First Employment: "Data Service Specialist" at [IRD Inc. in Saskatoon](http://www.irdinc.com/).
    
    Present Position: Statistician, Mabwell Therapeutics, Inc., Shanghai, China
    
    Publications: 
    * Longhai Li, Cindy X. Feng, and Shi Qiu* (2017), Estimating Cross-validatory Predictive P-values with Integrated Importance Sampling for Disease Mapping Models. [[slides]](/doc/talks/dmpvalues_ssc.pdf), [[R code]](/software/dmpvalues/dmpvalues-larynx.R), [arXiv:1603.07668](http://arxiv.org/abs/1603.07668), [Statistics in Medicine, Volume 36, Issue 14, Pages 2220-2236](http://onlinelibrary.wiley.com/doi/10.1002/sim.7278/full). 
    * Li, L., Qiu, S.*, Zhang, B.*, and Feng, C.X. (2016). Approximating Cross-validatory Predictive Evaluation in Bayesian Latent Variables Models with Integrated IS and WAIC. [arXiv 1404.2918](http://arxiv.org/abs/1404.2918), [[slides]](/doc/iis/iisslides-tongji.pdf), [Statistics and Computing, Volume 26, Issue 4, pp 881-897](http://link.springer.com/article/10.1007/s11222-015-9577-2). 

15. Masud Rana, M.Sc., 2012 (co-supervised with Prof. Shahed Khan)
    
    Thesis: [Spatial-Longitudinal Bent-Cable Model with an Application to Atmospheric CFC Data](/researchteam/theses/Thesis_mdr091.pdf)
    
    First Employments: Biostatistician at Clinical Research Support Unit by College of Medicine of University of Saskatchewan. 
    
    Publication: 
    * [A Statistical Investigation to Monitor and Understand Atmospheric CFC Decline with the Spatial-Longitudinal Bent-Cable Model.](http://www.ccsenet.org/journal/index.php/ijsp/article/view/17253) 

16. Zhengrong Li, M.Sc., 2012. 
    
    Thesis: [A Non-MCMC Procedure for Fitting Dirichlet Process Mixture Models](/researchteam/theses/zhli_thesis.pdf) 
    
    First Employment: Data Service Specialist at [IRD Inc. in Saskatoon](http://www.irdinc.com/).

## Undergraduate Students

1. George Chen, B.Sc., Computer Science, Simon Fraser University, June, 2025 - Aug. 25, 2025, Supervised.
2. Shruti Kaur, B.Sc., Computer Science and Statistics, May - Aug., 2025, Supervised.
3. George Chen, B.Sc., Computer Science, Simon Fraser University, May 7, 2023 - Aug. 25, 2023, Supervised.
4. Noah Little, B.Sc., Anatomy and Cell Biology, April 2022 - Aug. 31, 2022, Supervised.
5. Noah Little, B.Sc., Anatomy and Cell Biology, Aug. 2020 - Feb. 2021, Supervised.
6. Lifang Lei, B.Sc., Mechanical Engineering, Oct. 2020 - March 2021, Supervised.
7. Yanping Li, B.Sc., Business, Edward Business School, Feb. 2021 - June 2021, Supervised.
8. Hao Hu, B.Sc., Statistics, 2019-2020, Undergraduate Thesis Supervision, Supervised.
9. Steven Liu, B.Sc., Computer Science, July 2019 - Oct. 2020, Summer Research Assistant, Supervised.
10. Lina Li, B.Sc., Statistics, May 2020 - June 2020, Summer Research Assistant, Supervised.
    
    Project title: Investigation of Randomized Quantile Residuals
    
11. Steven Liu, B.Sc., Computer Science, June 17, 2019 - Aug. 31, 2019, Supervised.
    
    Project title: Development of an R package for Bayesian Hyper-LASSO Logistic Regression
    
    **Software:** \
    HTLR: [Bayesian Logistic Regression with Heavy-Tailed Priors](/software/BLRHL/index.html), [**[CRAN page]**](https://cran.r-project.org/web/packages/HTLR/index.html), [**[Github page]**](https://longhaisk.github.io/HTLR). HTLR was listed in [the top 40 new packages in October 2019](https://rviews.rstudio.com/2019/11/18/october-2019-top-40-new-r-packages/?mkt_tok=eyJpIjoiT1RabU5tVTFaR0ptTlRCbCIsInQiOiJXWFlONVZhcm44V1wvR25pNmJUb3BrU3h2NmxMN0pPZW9tdVZSelc2ZDRnUWxrbGcrUmcyRnhJdnAraXJCaUVhdkVvbFNRU1hLUEJCTXk1ZHJFSDBFNTBDXC9qZkxSYTdGcWNlclZjYndQdElINnRNRVNWeDZrMU55clQ2Q2dEOU9IIn0%3D) by R views of Rstudio.
    
12. Jian Su, B.Sc., Computer Science, May 1, 2018 - Aug. 31, 2018, Supervised.
    
    Project title: Development of Bayes Predictive Models based on Generalized Linear Mixed Models with application to microbiome data
    
13. Jiaqi Xiao, B.Sc., Economics, Research Assistant, May 2016 - Aug. 2016, Supervised.
14. Jiaqi Xiao, B.Sc., Economics, May 2015 - Aug. 2015, Supervised.
    
    Project title: Application of iIS and iWAIC to Compare Models for Economic Data.
    
    Employment: M.Sc. student at Queen's University
    
15. Zhouji Zheng, B.Sc., Mathematics, 2014-2015, undergraduate research assistant, Supervised.
    
    Project title: Application of Importance Sampling to Compare Bayesian Stochastic Volatility Models.
    
    Employment: M.Sc. student at the University of Toronto
    
16. Bei Zhang, B.Sc., Statistics, May 1, 2013 - Aug. 31, 2013, Supervised.
    
    Project title: Cross-validatory Model Checks with iIS for Logistic Random Effect Models
    
    Publication: [Approximating Cross-validatory Predictive Evaluation in Bayesian Latent Variables Models with Integrated IS and WAIC.](http://arxiv.org/abs/1404.2918)


<footer>
Last updated on `r format(Sys.time(), "%B %d, %Y")`.
</footer>    