# .streamlit/config.toml

[theme]

# Set the primary color.
# This color is used for widgets like st.button(type="primary"),
# st.checkbox, st.radio, st.slider accents, etc.
# Use a valid CSS hex color code (e.g., "#RRGGBB").

primaryColor="#FFA500"  # Example: Set primary color to Red

# --- Optional: You can customize other theme colors too ---
# backgroundColor="#FAFAFA"
# secondaryBackgroundColor="#EAEAEA"
# textColor="#111111"
# font="sans serif"
