GITHUB_APP_ID = "1222076" 
GITHUB_INSTALLATION_ID = "64845594" 
GITHUB_PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAsSY95MyWYU6nyG9Fv7Iqr61iqaKgUYSKflNnGa6RPk+32+BS
WDWIEsgTkDLuRL0vMy/yO7hNWByNYida6znVZ3K76A+JuVS1ONe9bcy9+ovsia6S
8kT9H9cg32cY9wa++MEBlFJM3MSGR52Yawv+2uhzRmDB9nzw3T7jm6LMTUukd030
Q9jnNH7YLGyCzG971QYQejroD9aM5Uu8TE/KcVeOV1HbWGhkFB/D069HeFJ+uAfs
jbNsZfYC1cNJkrP0m3HqqpUKYE+SVrz8rekZfggXpgCbnvQE6MyBYTF4jzq+jI34
IFlzIRju5EtetqNhFI+BR7HdJKsj3M7uxN+sVQIDAQABAoIBAE4eMwUGQvo+GTcF
+pgCFVjK+Msdb90CuZ/jX3+vv1TfCpDnZuiHEq5VlGruSqv9UScdaZB0QYctcBts
h2dbZYPs0HgRAga8F/4tBNe6hbxKn9BHL32udoDn+RMK/7NPQj+nvO6PLF3eO+iw
0lnCPGyEPPE4EdCEYCLwbKZhL/6VNOjZHpXzvF+uwlaPKh4NREbMW72TAIJMNYKo
Ukl9GxoeeGO4KCGigZQVVqZaJZ00sK+ON0alN8BwS8p0Kj1wIV23fWm7p1v9IPkR
TBNSidWduM+J8Y581u10fCW0ziV/WpUABLkEQi5SSZI1ykSfNiM4tpyqYc54QWNE
5kutwIECgYEA12jdXivlD8jaxz/6qJDrjRUK48l1Yhi52xrzvOHtUKkRbcysnZjS
q8wgIq+gQKW9LW6oLKmrdctBYAF0qWl/B3hdTRzaDLdz8/iSGBzeUj4WKlQdMvay
S9KCGPuDDTfzsKdYeDdRGsebS8M5IOR9o00/mbqBKq+AIFc7Nr7sQH0CgYEA0oe+
JzKu+blsRwR0ZcpZbastN969G3qhmoVyWeTqbNIlS1wwR55BQXP623ctJQRPZHQU
dz8WnHMFUFp9kUzv6hLPNfk5KApB8HIPfk2FHdhzVy5cS34SH+RWA/ZF5QgAb8HA
4D39uPODBh+NphPTg29g93vj7ahrrevHlATH+rkCgYEAn42WAm3i8gklO9bA9GC7
iLmgYk7TeoC0EX3qMerqnAdO2JR0+xq6WPQOjYKm4Zuh/2fqe4KFdO/DkbgiUGXK
6J6YBUksnaS452oj1GZ1qldAlcPOCPS/5feb06NgU8cw4pVhq1HV6k8VUU3eH+X+
xZmvVU/W4uYxskLKomdSmQUCgYEAmlERmt3V0AqQSYYEY9BsuKxuWrOT3h6HciI6
7ZWUF+v5lkGeygBASN/gkxnKJ4X/Q9yqW7YMtuTAkmOiAu1oNiVPaXqi4KyUJNEW
djgQSQ4tjUvYLyXb1zChtAnCtdylpUVaQYRvBDDKa6SZSZDiy0bKxt0y9zMqqrNW
+TJ/+1ECgYBPQNYhGOU2FDv0AUo0vE72g7OSkd1nm/fwUs1d3QwKwF1c7CbKx7Io
n8zCpt6rZP9OxaDw6Utq8ThAx5p3QSVp3Kxijb0rynu8vR2LnABTsB2xOpxaTz/Y
664k2Uxb9orJTgRTugE0Gue7vREUoyBEIPzXRc1+WFhO+T+1BmSrlw==
-----END RSA PRIVATE KEY-----"""