

```{=typst}
#align(right)[#text(size: 14pt, weight: "bold")[Form 1]]
#v(1em)
#grid(
  columns: (1fr, 1fr),
  row-gutter: 1em,
  [*Name:* #underline[Longhai Li]], [*Date:* #underline[June 30, 2027]],
  [*College:* #underline[Arts & Science]], [*Department:* #underline[Mathematics & Statistics]]
)
#v(0.5em)
#line(length: 100%)
#v(1em)
#align(center)[
  #strong[
    INFORMATION FOR UPDATE OF CURRICULUM VITAE -- NEW ITEMS \
    (ITEMS NOT PREVIOUSLY REPORTED) \
    The cut off date for items to be reported is JUNE 30.
  ]
]
```

```{=html}
<div style="text-align:right;"><span style="font-size:14pt; font-weight:bold;">Form 1</span></div>
<div style="margin-top:1em;">
  <table style="width:100%; border-collapse:collapse;">
    <tr>
      <td style="width:50%;"><strong>Name:</strong> <span style="text-decoration:underline;">Longhai Li</span></td>
      <td style="width:50%;"><strong>Date:</strong> <span style="text-decoration:underline;">June 30, 2027</span></td>
    </tr>
    <tr>
      <td><strong>College:</strong> <span style="text-decoration:underline;">Arts &amp; Science</span></td>
      <td><strong>Department:</strong> <span style="text-decoration:underline;">Mathematics &amp; Statistics</span></td>
    </tr>
  </table>
</div>
<hr style="margin:1em 0;">
<div style="text-align:center;">
  <strong>
    INFORMATION FOR UPDATE OF CURRICULUM VITAE -- NEW ITEMS<br>
    (ITEMS NOT PREVIOUSLY REPORTED)<br>
    The cut off date for items to be reported is JUNE 30.
  </strong>
</div>
```

---
engine: knitr
format:
  profweb-html: default
  profweb-typst: default
---

{{< include /_ritem.qmd >}}

```{=html}

```

::: {.course-tables}

:::

```{=html}
```

## 10. SUPERVISION AND ADVISORY ACTIVITIES

    

### 10.2 Graduate Student Supervision

`r ritem(2)` **Jing Wang**, Ph.D., Biostatistics, School of Public Health, Co-supervised with Prof. Li Xing, 2023–2026 (Transferred to other supervisor)

`r ritem()` **Malki Gunawardhana**, M.Sc., Statistics,  Math & Stat. 2026-present.

   

### 10.4 Supervision of Post-Doctoral Fellows and Research Associates

`r ritem(1)` Tingxuan Wu, University of Saskatchewan, Postdoc Research Associate,  Jan. 2025 – July 2026.

### 10.6 Thesis Committee Memberships

```{=html}
```

```{r}
#| label: thesis-committee
#| echo: false
#| message: false
#| warning: false
#| cache: true

library(dplyr)
library(gt)

# Create the dataframe using tribble for easy row-by-row data entry
committee_data <- tribble(
  ~`#`, ~NAME, ~DEG, ~PROGRAM, ~`TIME FRAME`, ~ROLE,
  31, "Tiansui Wu", "M.Sc.", "Biostatistics", "2025--Present", "Chair",
  30, "Prabhawi Kahatapitiye", "Ph.D.", "Statistics", "2025--Present", "Member",
  29, "Rasel Kabir", "Ph.D.", "Biostatistics", "2025--Present", "Chair",
  27, "Lina Li", "Ph.D.", "Biostatistics", "2023--Present", "Member",
  22, "Han Wang", "Ph.D.", "Sociology", "2020--Present", "Cognate"
)

# Render the gt table
committee_data |> 
  gt() |> 
  tab_options(
    table.width = pct(100),
    
    table.layout = "fixed",
    table.font.size = px(12), 
    container.overflow.x = TRUE,
    # --- remove all lines ---
    table.border.top.style = "hidden",
    table.border.bottom.style = "hidden",
    column_labels.border.top.style = "hidden",
    column_labels.border.bottom.style = "hidden",
    table_body.hlines.style = "none",
    table_body.vlines.style = "none",
    table_body.border.top.style = "hidden",
    table_body.border.bottom.style = "hidden",
    stub.border.style = "hidden"
  ) |> 
  cols_width(
    `#` ~ pct(5),
    NAME ~ pct(25),
    DEG ~ pct(5),
    PROGRAM ~ pct(20),
    `TIME FRAME` ~ pct(30),
    ROLE ~ pct(10)
  ) |>  
  opt_row_striping() |> 
  # --- gray header background + bold ---
  tab_style(
    style = list(
      cell_fill(color = "#d9d9d9"),
      cell_text(weight = "bold")
    ),
    locations = cells_column_labels()
  ) |> 
  cols_align(
    align = "center",
    columns = c(`#`, DEG, ROLE)
  ) 
```

```{=html}
```

## 12. PAPERS IN REFEREED JOURNALS

**2026-2027**

`r ritem(1)` Wu, T., Gao, WE, Feng, C., and Li, L., Z-residuals for Diagnosing Bayesian Models, *Journal of American Statistical Association*, under revision. [[**Slides**](https://bayesian-zresid-slides.longhai-li.workers.dev)]

 

                   

  

## 14. PRESENTATIONS

### 14.1 Invited Presentations

**2026-2027**

`r ritem(1)` [Z-residuals: A Versatile Diagnostic Framework for Bayesian Models](https://bayesian-zresid-slides.longhai-li.workers.dev/). Presented at: University of Toronto, Biostatistics Seminar, 1 September, 2026 

## 15. REPORTS AND OTHER OUTPUTS

### 15.1 Software Released Publicly {#research-software}

`r ritem(4)` Wu, T. and Li, L., 2027. `Zresidual`: Computing and Diagnosing Gaussian-like Residuals. [[pkgdown site]](https://tiw150.github.io/Zresidual/index.html). Version 0.1-0 on Github (April 2026); Version 0.2-0 on Github (August 2026); Version 0.2-0 on CRAN (August 2026).

`r ritem()` Li, L., 2026. R Functions for Computing Z-residuals for `survreg` and `coxph` Objects. [[URL]](https://longhaisk.github.io/software/NRSP/index.html).

`r ritem()` Li, L. and Liu, S., 2019--2026. `HTLR`: Bayesian Logistic Regression with Hyper-LASSO priors. DOI: 10.32614/CRAN.package.HTLR. [[CRAN]](https://cran.r-project.org/web/packages/HTLR/index.html) [[Github]](https://longhaisk.github.io/HTLR) [[URL]](https://longhaisk.github.io/software/BLRHL/index.html). Version 0.4 (2019), version 0.4-1 (2019), version 0.4-2 (2020), version 0.4-3 (2020), version 0.4-4 (2022), version 1.0 (2026).

`r ritem()` Li, L., 2011--2026. `BCBCSF`: Bias-corrected Bayesian Classification with Selected Features. DOI: 10.32614/CRAN.package.BCBCSF.  [[CRAN]](https://cran.r-project.org/web/packages/BCBCSF/index.html) [[URL]](https://longhaisk.github.io/software/BCBCSF/index.html). Version 0.0-0 (2011), version 0.0-1 (2011), version 0.0-2 (2012), version 1.0-0 (2013), version 1.0-1 (2015), updated to version 1.0-2 (2026).

### 15.2 Technical Reports {#techical-reports}

`r ritem(1)` Li, L., 2026. An entropy-based coefficient of determination with adjustment of optimization bias. [arXiv preprint arXiv:2608.06624](https://doi.org/10.48550/arXiv.2608.06624). August 2026. 

## 18. PRACTICE OF PROFESSIONAL SKILLS

### 18.1 Journal Refereeing

**2026-2027**
`r ritem(3)` Refereeing for *Biometrical Journal*, August 2026

`r ritem()` Refereeing for *Journal of Computational and Graphical Statistics*, July 2026

`r ritem()` Refereeing for *Bioinformatics*, July, 2026

## 19. ADMINISTRATIVE SERVICE

### 19.1 University Committees

**2026-2027**

`r ritem(1)` Chair, Collaborative Biostatistics Program, University of Saskatchewan.

```{=html}
```

```{=typst}
#colbreak()

#align(right)[#text(size: 14pt, weight: "bold")[Form 2]]
#v(1em)
#grid(
  columns: (1fr, 1fr),
  row-gutter: 1em,
  [*Name:* #underline[Longhai Li]], [*Date:* #underline[June 30, 2027]],
  [*College:* #underline[Arts & Science]], [*Department:* #underline[Mathematics & Statistics]]
)
#v(0.5em)
#line(length: 100%)
#v(1em)
#align(center)[
  #strong[
    INFORMATION FOR UPDATE OF CURRICULUM VITAE \
    (REVISION OF ITEMS PREVIOUSLY REPORTED AND CONSIDERED) \
    #v(0.5em)
    The cut off date for items to be reported is JUNE 30.
  ]
]
#v(2em)
#align(center)[*Nothing to report for timeframe: 2026-2027*]
```

```{=html}
<div style="page-break-before: always; text-align:right;"><span style="font-size:14pt; font-weight:bold;">Form 2</span></div>
<div style="margin-top:1em;">
  <table style="width:100%; border-collapse:collapse;">
    <tr>
      <td style="width:50%;"><strong>Name:</strong> <span style="text-decoration:underline;">Longhai Li</span></td>
      <td style="width:50%;"><strong>Date:</strong> <span style="text-decoration:underline;">June 30, 2027</span></td>
    </tr>
    <tr>
      <td><strong>College:</strong> <span style="text-decoration:underline;">Arts &amp; Science</span></td>
      <td><strong>Department:</strong> <span style="text-decoration:underline;">Mathematics &amp; Statistics</span></td>
    </tr>
  </table>
</div>
<hr style="margin:1em 0;">
<div style="text-align:center;">
  <strong>
    INFORMATION FOR UPDATE OF CURRICULUM VITAE<br>
    (REVISION OF ITEMS PREVIOUSLY REPORTED AND CONSIDERED)<br>
    <br>
    The cut off date for items to be reported is JUNE 30.
  </strong>
</div>
<div style="margin-top:2em; text-align:center;"><em>Nothing to report for timeframe: 2026-2027</em></div>
```

