---
title: "STAT 342 Mathematical Statistics"
engine: knitr
format: html
metadata-files:
  - ../../_website.yaml
---

## Description

This course deals with basic probability concepts at a moderately rigorous level. Topics include: probability spaces, conditional probability and independence, discrete and continuous random variables, standard probability models, expectations, moment generating functions, transformation of random variables, sampling distributions, limiting theory, and elementary statistical inference. The lecture notes follows closely to the textbook: [Introduction to Mathematical Statistics by Hoggs, Mckean, and Craig](https://www.amazon.ca/Introduction-Mathematical-Statistics-Robert-Hogg/dp/0321795431).

## List of Lectures and Topics

### Introduction to Statistical Inference

* **Lecture 1:** [Introduction](Introduction%20to%20Stat%20Models%20and%20Sampling%20Distributions.pdf)

### Probability Theory for A Single Random Variable

* **Lecture 2:** [Axioms of Probability](Lec02.key.pdf)
* **Lecture 3:** [Conditional Probability and Bayes Rule](Lec03.key.pdf)
* **Lecture 4:** [Independence of Events](Lec04.key.pdf)
* **Lecture 5:** [Random Variables and Cumulative Distribution Function (I)](Lec05.key.pdf)
* **Lecture 6:** [Random Variables and Cumulative Distribution Function (II)](Lec06.key.pdf)
* **Lecture 7:** [Probability Density Function and Transformation of a Single Random Variable](Lec07.key.pdf)
* **Lecture 8:** [Expectation, Moment Generating Function, Chebyshev Inequalities](Lec08.key.pdf)
* **Lecture 9:** [Jensen Inequality and Joint Distribution](Lec09.key.pdf)

### Random Vector

* **Lecture 10-11:** [Expectation for Joint Distribution, Moment Generating Function, and Transformation of Random Vector](Lec10-11.key.pdf)
* **Lecture 12:** [Conditional Expectation, Iterative Expectation Formula, Decomposition of Variance](Lec12.key.pdf)
* **Lecture 13:** [Correlation coefficient and Independence of Random Variables](Lec13.key.pdf)
* **Lecture 14:** [Extensions to More than 2 Random Variables, Linear Combination](Lec14.key.pdf)
* **Lecture 15:** [Bernoulli, Binomial, Multinomial Distribution](Lec15.key.pdf)
* **Lecture 16:** [Poisson and Gamma](Lec16.key.pdf)
* **Lecture 17:** [Exponential, Erlang, Poisson Process, Normal Distribution](Lec17.key.pdf)
* **Lecture 18:** [Chi-square distribution, Student's Theorem](Lec18.key.pdf)
* **Lecture 19:** [t and F distribution, Mixture distribution](Lec19.key.pdf)

### Asymptotic Theory

* **Lecture 20:** [Convergence in Probability, Law of Large Numbers, Consistency of sample mean and Variance](Lec20.key.pdf)
* **Lecture 21:** [Convergence in Distribution, Central Limit Theorem, Continuous Mapping and Slustky Theorems, Applications to Sample Means.](Lec21.key.pdf)