project:
  type: book
  output-dir: .
execute:
  dir: file
  cache: true
# Global format settings from your chapter YAML
format:
  html:
    embed-resources: false
    # Set to false globally since you inject your own TOC
    toc: false 
    toc-title: "Contents"
    toc-depth: 3
    page-layout: full
    code-fold: true
    number-sections: true
    df-print: paged
    highlight-style: tango
    # Global JS/CSS includes
    include-in-header:
      text: |
        <link rel="stylesheet" href="/resources/mystyles.css?v=2">
        <script src="/resources/loadtoc.js" defer></script>
book:
  title: "Introduction to Statistical Methods for Research"
  author:
  - name: "Longhai Li"
    url: "https://longhaisk.github.io/"
  date: today

  chapters:
    - index.qmd
    - unit2-slr/slr.qmd
    - unit3-mlr/mlr.qmd
    - unit3-mlr/residuals.qmd
    - unit4-lr/logistic.qmd
    - unit5-factor/crbd.qmd
    - unit6-factorial/factorial.qmd

# Centralized chapter titles (keys are paths relative to the book dir)
chapter-titles:
  index.qmd: "Welcome"
  unit2-slr/slr.qmd: "Simple Linear Regression"
  unit3-mlr/mlr.qmd: "Multiple Linear Regression"
  unit3-mlr/residuals.qmd: "Residual Diagnostics"
  unit4-lr/logistic.qmd: "Logistic Regression"
  unit5-factor/crbd.qmd: "Complete Randomized Block Design"
  unit6-factorial/factorial.qmd: "Factorial Experiments"

filters:
  - clean-chapters.lua

