project:
  type: book
  output-dir: .
execute:
  dir: file
  cache: true
  echo: true
  warning: false
  message: false
  fig-width: 6
  fig-height: 6
  freeze: auto
# Global format settings from your chapter YAML

format:
  html:
    theme: cosmo
    toc: false
    toc-title: "Contents"
    toc-depth: 3
    page-layout: full
    code-fold: true
    number-sections: true
    df-print: paged
    highlight-style: tango
    include-in-header:
       text: |
        <script src="../resources/pagetoc.js" defer></script>
        <link rel="stylesheet" href="../mystyles.css">
  pdf:
      documentclass: scrbook
      toc: true
      number-sections: true
      colorlinks: true
      mainfont: "Times New Roman"
      geometry:
        - top=30mm
        - left=20mm
from: markdown+tex_math_single_backslash+tex_math_dollars


book:
  title: "Statistical Methods for Research"
  author:
  - name: "Longhai Li"
    affiliation: "University of Saskatchewan"
    url: "https://longhaisk.github.io/"
  date: today

  chapters:
    - index.qmd
    - unit1-introR/introR.qmd
    - unit2-slr/slr.qmd
    - unit3-mlr/mlr.qmd
    - unit4-lr/logistic.qmd
    - unit5-factor/crbd.qmd
    - unit6-factorial/factorial.qmd


