project:
  type: book
  output-dir: .
execute:
  dir: file
  cache: true
# Global format settings from your chapter YAML

format:
  html:
    pandoc_args:
      - "--shift-heading-level-by=1"
    # Set to false globally since you inject your own TOC
    toc: false
    toc-title: "Contents"
    toc-depth: 3
    page-layout: full
    code-fold: true
    number-sections: true
    df-print: paged
    highlight-style: tango
    # Global JS/CSS includes
    include-in-header:
      text: |
        <link rel="stylesheet" href="/resources/mystyles.css?v=2">
        <script src="/resources/loadtoc.js" defer></script>
book:
  title: "Statistical Methods for Research"
  author:
  - name: "Longhai Li"
    affiliation: "University of Saskatchewan"
    url: "https://longhaisk.github.io/"
  date: today

  chapters:
    - index.qmd
    - unit2-slr/slr.qmd
    - unit3-mlr/mlr.qmd
    - unit3-mlr/residuals.qmd
    - unit4-lr/logistic.qmd
    - unit5-factor/crbd.qmd
    - unit6-factorial/factorial.qmd

filters:
  - clean-chapters.lua
  
  


