
project:
  type: book
  output-dir: .

book:
  title: "Introduction to Statistical Methods for Research"
  chapters:
    - index.qmd
    - ../unit2-slr/slr.qmd
    - ../unit3-mlr/mlr.qmd
    - ../unit3-mlr/residuals.qmd
    - ../unit4-lr/logistic.qmd
    - ../unit5-factor/crbd.qmd
    - ../unit6-factorial/factorial.qmd

# Turn off chapter title blocks globally (we’ll replace with the first # heading)
filters:
  - strip-meta.lua

format:
  html:
    number-sections: true
    toc: true
    toc-depth: 2
