---
title: "[STAT 812: Computational Statistics](../stat812.html)"
subtitle: "MCMC Sampling with JAGS"
date: "September 2018"
author: "Longhai Li"
output:
  html_document:
       theme: united
       toc: true
       toc_float: true
       number_sections: true
       highlight: tango
       fig_width: 10
       fig_height: 8
  pdf_document:
    toc: yes
    fig_height: 6
    fig_width: 10
    number_sections: yes
---


```{r}

library ("R2jags")
```

# Example of Normal Data

##Define the model for jags


```{r}
normmodel <- '
model{
	mu ~ dnorm (0, 0.000001)
	prec ~ dgamma (1, 0.000001)
	for (i in 1:n)
	{
		x[i] ~ dnorm(mu,prec)
	}
	sigma <- 1/sqrt(prec)
}

'

write (normmodel, file = "normmodel.bug")

```

## Use JAGS to simulate MCMC 

```{r}
# give a list of names of R objects that will be fixed during MCMC sampling
data <- list (x = rnorm (100, 100, 5), n = 100)


# define a function to generate initial values for parameters
inits <- function ()
{
  list (mu = rnorm (1, 10, 0), prec = (1/10)^2)
}
# call jags to simulate MCMC
fitj <- jags (model.file = "normmodel.bug",
				data = data, inits = inits, 
        parameters = c("mu", "sigma"),
				n.chains = 4, n.thin = 1, n.burnin = 1000, n.iter = 5000)


traceplot (fitj, varname = "mu", xlim = c(1, 10))
# summary mcmc fit 
fitj
```


## Inference with MCMC Samples

```{r}
# plot the markov chain for the mu0 in the 1st chain 

traceplot (fitj)

# convert to MCMC object
as.mcmc (fitj) -> fitj.mcmc

summary (fitj.mcmc)

# the first chain
fitj.chain1 <- fitj.mcmc[[1]]

# all chains
fitj.matrix <- as.matrix (fitj.mcmc)

# traceplot
traceplot (fitj.mcmc)

plot(fitj.chain1[,2:3])

# scatterplot
plot(fitj.matrix[,2:3])


```

# Example of Logistic Regression
```{r}
library ("R2jags")

############################# define the model for jags #######################
regmodel <- '
model{
beta0 ~ dnorm (0, 0.000001)
beta1 ~ dnorm (0, 0.01)
beta2 ~ dnorm (0, 0.01)
for (i in 1:n)
{
  y[i] ~ dbern (ilogit(beta0 + beta1 * x1[i] + beta2 * x2[i]))
}

}

'

write (regmodel, file = "regmodel.bug")

##################### use jags to simulate MCMC ###############################
n <-50
ilogit <- function (x) 1/(1 + exp (-x))
x1 <- rnorm (n, 0, 2)
x2 <- rnorm (n, 0, 2)
truebeta <- c(0,2,2)
y <- rbinom (n, 1, ilogit( truebeta[1] + truebeta[2]*x1 + truebeta[3]*x2))
data <- list (x1 = x1, x2 = x2, y = y, n = n)

# look at the data
plot (x1,x2,col=y+1, pch = y+1)
abline(a=-truebeta[1]/truebeta[3],-truebeta[2]/truebeta[3])

# define a function to generate initial values for parameters
inits <- function ()
{
  list (beta0 = 0, beta1 = 0, beta2 = 0)
}
# call jags to simulate MCMC
fitj <- jags (model.file = "regmodel.bug",
				data = data, inits = inits, 
        parameters = c("beta0", "beta1","beta2"),
				n.chains = 4, n.thin = 1, n.burnin = 1000, 
        n.iter = 10000)
traceplot (fitj,ask=FALSE)

# summary mcmc fit 
fitj

fitj.mcmc <- as.mcmc (fitj)

fitj.matrix <- as.matrix (fitj.mcmc)


colnames (fitj.matrix)

# sample from posterior of (beta0, beta1)
plot (fitj.matrix[seq (1000,10000, by = 10),c("beta0", "beta1")], type = "p")

# sample from posterior of (beta1, beta2)
plot (fitj.matrix[seq (1000,10000, by = 10),c("beta1", "beta2")], type = "p")

# density of beta0
plot(density(fitj.matrix[,"beta0"]))

# density of beta1
plot(density(fitj.matrix[,"beta1"]))

# density of beta2
plot(density(fitj.matrix[,"beta2"]))

#Find Psuedo MLE
imle <- which.min(fitj.matrix[,"deviance"]) 
mlebeta <- fitj.matrix[imle,]; mlebeta

# look classification boundaries
plot (x1,x2,col=y+1, pch = y+1) 
# MCMC Estimates
for (i in seq (1000,5000, by = 50)) {
    abline (a = -fitj.matrix[i,"beta0"]/fitj.matrix[i,"beta2"],
            b = -fitj.matrix[i,"beta1"]/fitj.matrix[i,"beta2"],
            col = "grey")
}
# True Values
abline(a=-truebeta[1]/truebeta[3],b=-truebeta[2]/truebeta[3],
       col="black", lwd=3)

abline(a=-mlebeta[1]/mlebeta[3],b=-mlebeta[2]/mlebeta[3],
       col="red", lwd=3)
points (x1,x2,col=y+1, pch = y+1)

legend("bottomleft", legend=c("TRUE", "MLE", "MCMC"), 
       col = c("black", "red", "grey"), lty = c(1,1,1))

# look at classification boundary coefficient
plot(density(fitj.matrix[,"beta1"]/fitj.matrix[,"beta2"]))
abline(v=truebeta[2]/truebeta[3], col="black")
abline(v=mlebeta[2]/mlebeta[3], col="red")

# look at classification sharpness coefficient
# plot(density(fitj.matrix[,"beta1"]^2+fitj.matrix[,"beta2"]^2))
# abline(v=truebeta[2]^2+truebeta[3]^2, col="black")
# abline(v=mlebeta[2]^2+mlebeta[3]^2, col="red")

```


# Example of Mixture Model

```{r cache=TRUE}
library ("R2jags")
library ("MASS")

# user should provide ifold
mixmodel <- '
var
N,           # number of observations
K,           # number of components
y[N],        # observations
Z[N],        # true groups (labelled 1,2)
mu[K],       # means of two groups
tau.mu,     	 # prior precision for mu
tau[K],      # sampling precision
sigma[K],    # sampling standard deviation
P[K],        # proportion in first group
alpha[K],    # prior parameters for proportions
ind[N,K],    # indicator function for group membership
tol[K],      # total number of observations in each group
Itot[K];     # Censored indicator for tot (1 if tot[i] > 0; 0 otherwise)


model {
    for (k in 1:K){
        mu[k]  ~ dnorm(20, 1.0E-4);
        tau[k] ~ dgamma(0.01, 0.01 * 20);
        sigma[k]     <- 1/sqrt(tau[k]);
    }
    P[]    ~ ddirch (alpha[]);    # prior for mixing proportion
    for (i in 1:N){
        y[i]  ~ dnorm(mu[Z[i]],tau[Z[i]]);       
        Z[i]  ~ dcat(P[]);
        for (k in 1:K) {
            ind[i,k] <- (Z[i] == k);
        }
    }
    for (k in 1:K) {
        tot[k] <- sum(ind[,k]);
        Itot[k] ~ dinterval(tot[k], 0);
    }
    
    for (i in 1:N){
        logp.tr [i] <- log (dnorm (y[i], mu[Z[i]], tau[Z[i]]));   
    }
    
} 
'

write (mixmodel, file = "mixmodel.jags")



K <- 2 ## number of components

y <- sample(c(rnorm (30, mean = 20), rnorm (70, mean=23)))
hist (y, nclass=15)
N <- length (y)
Itot <- rep (1, K)
alpha <- rep (1, K)

eyesdata <- list ( y = y, K = K, N = N, Itot = Itot, alpha = alpha)

inits <- function ()
{
    list (#mu = rnorm (K, mean (y),20), 
          #tau = rep(1/var (y),K), 
          Z = sample (1:K, N, replace = T) )
}

mixmodel.jags <- jags (data = eyesdata,  inits = inits, model.file = "mixmodel.jags", 
			parameters =  c("P", "mu","sigma"),       
            n.thin = 5, n.iter = 5000, n.chain = 1)

mixmodel.mcmc <- as.mcmc (mixmodel.jags)

summary (mixmodel.mcmc)

traceplot (mixmodel.mcmc)
```

