---
title: "STAT 812/420 Computational Statistics"
engine: knitr
format: profweb-html
---

## Description

This course covers the fundamental concepts in computational methods used the areas of statistics, machine learning, and data sciences. The topics include Introduction to R programming; Computer Arithmetics (Overflow, Underflow, Rounding Error); Monte Carlo Methods (RNG, Inverting CDF Sampling, Simulation for Estimation and Testing); Maximum Likelihood Estimation (Univariate Optimization, Multivariate Optimization, EM Algorithm); and Bayesian Inference & MCMC (Intro to Bayesian Inference, Numerical Quadrature, Laplace Approximation, Rejection Sampling, Importance Sampling, Convergence, Gibbs Sampling, Metropolis-Hastings Sampling, General-purpose Samplers like JAGS and STAN). After learning this course, students are expected to gain an understanding of the algorithms behind these statistical inferential methods, be able to develop new statistical methods, use computers to investigate the properties of statistical methods, and implement a combination of standard statistical toolkits for analyzing real data sets.

## Prerequisites

* Multivariate calculus (MATH 225)
* Linear algebra (MATH 164)
* Calculus-based Probability (eg. STAT 342 or STAT 241)
* Multiple Linear Regression (eg. STAT 344)


## Course Materials

1. [HTML Book](https://longhaisk.github.io/compstat)
2. [Handwritten Lecture Notes](https://usaskca1-my.sharepoint.com/:f:/g/personal/lol553_usask_ca/IgBLkZz42Ct3RJgzJRi7660_AftKSZxRzlDvsYLxoJe7v-0?e=SRhsih)


## Syllabi

1. [2026 Fall Term](./syllabus2026.html)
