---
title: "STAT 845 Statistical Methods for Research"
engine: knitr
format: html
metadata-files:
  - ../../_website.yaml
---

## Description

Statistical methods as they apply to scientific research, including: Experimental design, blocking and confounding, analysis of multifactor experiments, multiple regression, and model building.

**Prerequisite(s):** STAT 242 or 245 or permission of the instructor.

## Lecture Notes and Course Materials

[HTML](book/){.btn .btn-outline-primary role="button"}
[PDF](book/stat_inference_learning.pdf){.btn .btn-outline-primary role="button"}
[Source qmd Code](https://github.com/longhaiSK/longhaiSK.github.io/tree/main/teaching/stat845_rdemo){.btn .btn-outline-primary role="button"}
[Slides/Assignments/Solutions](https://usaskca1-my.sharepoint.com/my?id=%2Fpersonal%2Flol553%5Fusask%5Fca%2FDocuments%2Fteaching%2Fstat845%2Dpublic&ga=1&startedResponseCatch=true){.btn .btn-outline-primary role="button"}

::: {.callout-note}
The link to OneDrive slides is password-protected (released on Canvas).
:::

## Tentative Course Schedule 🗓️

| Academic Week | Calendar Week | Date of First Monday | Topics | Remarks |
|:---:|:---:|:---|:---|:---|
| 1 | 36 | Sep 01 | | Sep 04: First day of class |
| 2 | 37 | Sep 08 | Unit 0: Introduction <br> Unit 1: [Quick Introduction to R](book/unit1-introR/introR.html) | |
| 3 | 38 | Sep 15 | Unit 2: [Simple Linear Regression](book/unit2-slr/slr.html) | |
| 4 | 39 | Sep 22 | Unit 3: [Multiple Linear Regression](book/unit3-mlr/mlr.html) | |
| 5 | 40 | Sep 29 | Unit 3: ANOVA | Sep 30: No Class |
| 6 | 41 | Oct 06 | Unit 3: Residual and Leverage | |
| 7 | 42 | Oct 13 | Unit 3: Step-wise Regression, Multilinearity, VIF | Oct 13: Thanksgiving (No class) <br> **Oct 17: Assignment 1 due** |
| 8 | 43 | Oct 20 | Unit 4: [Logistic Regression](book/unit4-lr/logistic.html) | **Oct 21: Midterm 1** |
| 9 | 44 | Oct 27 | Unit 5: [One-factor Design](book/unit5-factor/crbd.html) | |
| 10 | 45 | Nov 03 | Unit 5: Linear Models for One-way ANOVA | **Nov 07: Assignment 2 due** |
| [Reading Week]{style="color: #388e3c;"} | 46 | Nov 10 | — | Fall Reading Week (No classes) |
| 11 | 47 | Nov 17 | Unit 5: One-way ANOVA, Tukey Comparison | |
| 12 | 48 | Nov 24 | Unit 5: RCBD | **Nov 27: Midterm 2** |
| 13 | 49 | Dec 01 | Unit 6: [Factorial Design](book/unit6-factorial/factorial.html) | Dec 04: Last lecture <br> **Dec 05: Assignment 3 due** |

::: {.important-note}
**Important Notes:** The official schedule and due dates for all assignments and tests are posted on Canvas.
:::

## Computing Facilities

Learning computational techniques using statistical software is an integral part of statistical theory and applications. The R statistical software will be introduced as a tool to understand the applications of statistical techniques. The objective is to help you develop skills for data analysis. Assignment problems may require the use of R to analyze problems, and present and explain answers. You can use python to complete the assignments, but instructions are not provided in the class.

* Download [Rstudio](https://www.rstudio.com/products/rstudio/download/) and [R](https://www.r-project.org/) on your own computer.
* [Posit Cloud](https://posit.cloud/)
* Online Jupyter notebook: [usask.syzygy.ca](https://usask.syzygy.ca/)
* [Google's Colab](https://colab.research.google.com/) with R/Python chosen as the runtime type

## List of Topics

### Part I: Regression Analysis

* **Unit 2: Simple Linear Regression.** Model Description and Assumptions, Least Squares Formulation, Properties of the Least Squares Estimators, Hypothesis Testing, Confidence Intervals, Prediction, Model Adequacy Checking, Correlation, Regression on Transformed Variables.
* **Unit 3: Multiple Linear Regression.** Model Description and Assumptions, Least Squares Formulation, Properties of the Least Squares Estimators, Hypothesis Testing, Confidence Intervals, Prediction, Model Adequacy Checking, Polynomial Regression Models, Categorical Regressors and Indicator Variables, Selection of Variables and Model Building, Multicollinearity.
* **Unit 4: Logistic Regression.** Regression with a Binary Response, Statistical Inference.

### Part II: Design and Analysis of Experiments

* **Unit 5: Single-Factor Experiments.** Designing Experiments, Completely Randomized Single-Factor Experiment, Randomized Complete Block Design.
* **Unit 6: Factorial Experiments.** Two-Factor Factorial Experiments, General Factorial Experiments, $2^k$ Designs, Single Replicate of the $2^k$ Designs, Blocking and Confounding.

## Extended Learning Resources

1. [STAT 845 on Canvas](https://canvas.usask.ca/courses/108290)
2. [More on Using R](/teaching/stat812_rdemo/rdemo/unit01_introduction_longer.html)
3. [STAT 245: Introductory Statistics](https://longhaisk.github.io/teaching/stat245_rdemo/index.html)
4. [Learning Statistics with R (online book)](https://learningstatisticswithr.com/book)
5. [Multiple Linear Regression with R](https://learningstatisticswithr.com/book/regression.html)
6. [STAT 345: Design and Analysis of Experiments](https://longhaisk.github.io/teaching/stat345/index.html)




<footer>
Last updated on `r format(Sys.time(), "%B %d, %Y")`.
</footer>
