---
title: "STAT 443/851 Theory of Linear Models (University of Saskatchewan, 2026-01)"
format: 
  html: 
    theme: cosmo
    toc: true
    page-layout: full
    echo: true
    code-fold: true
    df-print: paged
    highlight-style: tango
    css: syllabusstyles.css
  typst: default


---


## Description
This course is a rigorous examination of the general linear models using vector space theory, in particular the approach of regarding least square as projection. The topics includes: vector space; projection; matrix algebra; generalized inverses;  quadratic forms; theory for point estimation; theory for hypothesis test; theory for non-full-rank models. 

**Prerequisite(s):** MATH 164 (formerly MATH 264) or MATH 266, STAT 342, and STAT 344 or 345.

## Instructor
[Longhai Li](https://longhaisk.github.io/), Professor, <br>
Department of Mathematics and Statistics, University of Saskatchewan<br>
Email: longhai.li@usask.ca.

## Times and Places
Lecture Classroom: MCLN 242.1, MWF 9:30-10:20; Office hour: TBA; Lab: no lab.


## Course Materials

* [My Lecture Notes](.) is the primary source for learning.
* [This one-drive folder](https://usaskca1-my.sharepoint.com/:f:/g/personal/lol553_usask_ca/IgBmn-cp6aVuSIH_zsG-r2pcAXPJ4jdZPgUtcl8c20GipDo?e=o9xSaS) releases the assignments, tests, and their solutions if available.
* Recommended reading: LINEAR MODELS IN STATISTICS, Second Edition, by Alvin C. Rencher and G. Bruce Schaalje, ISBN 978-0-471-75498-5 (cloth). *The book is not required but it is good to have it.*

## Learning Outcomes

By the completion of this course, students will be expected to:

1.  **Utilize Vector Space Theory:** Apply concepts of vector spaces, subspaces, and orthogonal projections to provide a geometric interpretation of least squares estimation and the general linear model.
2.  **Apply Matrix Algebra:** Employ advanced matrix methods, including spectral theory, generalized inverses, to manipulate linear equations and solve for estimator properties.
3.  **Derive Distributional Properties:** Derive the properties of multivariate normal vectors and quadratic forms, utilizing Cochran’s Theorem to prove the independence and Chi-square distribution of regression sums of squares required for valid hypothesis testing.
4.  **Construct Statistical Inference:** Apply the theory of multiple regression to construct confidence regions and execute hypothesis tests (F-tests) for the general linear hypothesis.
6.  **Analyze Non-Full-Rank Models:** Distinguish between estimable and non-estimable functions in non-full-rank models (e.g., ANOVA frameworks) and formulate appropriate tests for these scenarios.

## Tentative Schedule
| Academic Week | Calendar Week | Date of Monday | Topic | Remarks |
|:---:|:---:|:---|:---|:---|
| 1 | 2 | Jan 05 | **1. Vector Space and Projection** | Jan 07: First day of class |
| 2 | 3 | Jan 12 | **1. Vector Space and Projection** (Cont'd) | |
| 3 | 4 | Jan 19 | **2. Matrix Algebra** | **Jan 25: Assignment 1 due** |
| 4 | 5 | Jan 26 | **2. Matrix Algebra** (Cont'd) | |
| 5 | 6 | Feb 02 | **3. Distribution of Multivariate Normal** | |
| 6 | 7 | Feb 09 | **4. Distribution of Quadratic Forms** | |
| N/A | 8 | Feb 16 | — | **Reading Week – No classes**|
| 7 | 9 | Feb 23 | **4. Distribution of Quadratic Forms** (Cont'd) |**Mar 01: Assignment 2 due**  |
| 8 | 10 | Mar 02 | **5. Theory for Multiple Regression** | **Mar 06: Midterm (during class)** |
| 9 | 11 | Mar 09 | **5. Theory for Multiple Regression** (Cont'd) | |
| 10 | 12 | Mar 16 | **5. Theory for Multiple Regression** (Cont'd) | |
| 11 | 13 | Mar 23 | **6. Non-full-rank Models** | |
| 12 | 14 | Mar 30 | **6. Non-full-rank Models** (Cont'd) | **Apr 05: Assignment 3 due** |
| 13 | 15 | Apr 06 | **Review** | Apr 06: Last lecture |

: {.schedule-table tbl-colwidths="[10,10,15,40,25]"}

::: {.callout-note}
**Important Notes:** The official schedule and due dates for all assignments and tests are posted on Canvas.
:::



## Evaluation

### Grading Scheme
**3 assignments: 3x10% = 30%,  1 term test:  20%,  final exam: 50%.**

### Assignments and Tests
**Assignment questions are released in the one-drive folder**. You will submit your solutions via Canvas. **If you miss an assignment without proper excuse, the weight will NOT be shifted to the final.** Undergraduate students will be assigned with different assignments and tests.

### Assignments

* I will accept late assignments only for three (3) days beyond the due date. The penalty for your delay is 10 percentage points per day of lateness from the value of the assignment (including weekends). **Extensions are only granted in rare instances (notably as a result of family or medical emergencies) and upon receipt of adequate documentation/proof.**
* Answer the questions in the order they appear in the assignment. Neatness is important.
* Solutions to problems are to be included. Hence, simple answers without work will receive few (or no!) marks.
* Most problems in statistics have a “real-life” basis. Hence, solutions should include not only numerical solutions but also a statement as to what the numbers say about the problem.
* The work handed in must not be an exact duplicate of others.
* Submitting Assignments: The assignment can be typed and/or handwritten. Save your assignment as **one PDF file** (for handwritten assignments, feel free to take a picture/scan of your work and save it as one PDF file). Upload the **PDF file** as an assignment submission in Canvas.
* More details will be provided ahead of each assignment.
* Due Date: See Course Schedule.

### Midterm
* The midterm is given in class period.
* Midterms must be written on the dates scheduled. Students must do midterms completely on their own. More details (including syllabus) will be provided ahead of each midterm.
* Type: Short-answer questions, problem-solving, open-book.
* Calculator: A scientific calculator is allowed.
* Make-up exam will not be given. If you miss an exam for a legitimate reason (e.g., illness, emergency) and notify me within 48 hours of the scheduled exam, the weight of the missed exam will be transferred to the final exam.

### Final Exam
* Scheduling: Final examinations may be scheduled at any time during the examination period; students should therefore avoid making prior travel, employment, or other commitments for this period. If a student is unable to write an exam through no fault of their own for medical or other valid reasons, documentation must be provided and an opportunity to write the missed exam may be given. Students are encouraged to review all examination policies and procedures: [http://students.usask.ca/academics/exams.php](http://students.usask.ca/academics/exams.php).
* The final exam will cover material of the entire course. More details will be provided ahead of the exam.
* Length: 3-hour in-person exam.
* Type: Short-answer questions, problem-solving, open-book.

### Criteria That Must Be Met to Pass
The **final exam is a required component of the course**. Students must complete the final exam in order to be eligible to receive a passing grade in this class.

## Attendance Expectation
Attendance is highly correlated with student performance. While a syllabus and suggested readings are provided, it is not an adequate substitute for attending class. Your **attendance is highly recommended** but not required, and you will not be graded on your attendance.

## Recording of the Course
Recording of the lectures will only be allowed in certain circumstances. Please see the instructor for information on how to receive approval. In general, there will be no videos available for in-person lectures. Therefore, **attendance is strongly recommended**.

## Use of Generative AI and Electronic Devices

**1. AI for Learning vs. Assessment**
Students are free (and encouraged) to use Generative AI tools (such as ChatGPT, Claude, or Copilot) as a study aid to understand course concepts, debug code, or explain complex theorems. However, **all submitted work for assignments must be your own.**

* **Assignments:** You must write your own solutions. Directly copying text, derivations, or code from an AI tool and submitting it as your own is considered plagiarism.
* **Penalty:** If there is any evidence that a solution has been copied from an AI source without understanding or attribution, a **severe penalty** (up to receiving a 0% on the assignment and a formal report of Academic Dishonesty) will be applied.

**2. Electronic Devices During Tests**
All term tests and the final exam are **Open Book**, meaning you may bring printed notes, textbooks, and lecture slides.

* **No Electronic Devices:** You are **NOT allowed** to use laptops, tablets, smartwatches, or any other electronic devices during the exam.
* **Phone Exception:** You are permitted to bring a smartphone, but it must remain stowed away during the writing period. It may **only** be used at the very end of the exam for the specific purpose of taking photos of your answer sheets for submission (if required). Using the phone for any other reason during the exam will be treated as academic misconduct.

