---
title: "STAT 850/442 Statistical Inference"
engine: knitr
format: html
metadata-files:
  - ../../_website.yaml
---


## Description

This course presents a rigorous theoretical treatment of statistical inference, offering a comparative analysis of frequentist and Bayesian paradigms. The curriculum explores several core areas of statistical theory, including Likelihood theory (Sufficient Statistic, Bartlett's Identities, Cramér-Rao Lower Bound, Exponential Families) and the mechanics of Maximum Likelihood Estimation (Score, Fisher Information, Newton-Raphson Methods, Asymptotics of Maximum Likelihood Estimators, Akaike Information Criteria, Deep Learning). The course also covers hypothesis testing and optimal point estimation through the lens of the Likelihood ratio test (Neyman-Pearson Lemma, Monotone Likelihood Test, Likelihood-based Tests) and UMVUE (Complete Statistic, Uniformly Minimum Variance Unbiased Estimators/Tests). Additionally, the syllabus addresses foundational concepts in Decision theory (Risk Function, Minimaxity Theorem) and provides a comprehensive treatment of Bayesian inference (Posterior, Bayes Rules, Bayes Risk, Minimax Rules, James-Stein Estimator, Empirical Bayes, Hierarchical Bayesian, MCMC, Case Study).

## Prerequisite(s) 

This course requires a strong command of multivariate calculus, alongside a rigorous foundation in intermediate probability theory including **asymptotic theorey for probability**. Students should also possess prior exposure to applied statistical methods and familiar with basic statistical concepts such as p-value and confidence internal. 

## Lecture Notes and Course Materials

[HTML](mathstat/index.html){.btn .btn-primary role="button"}
[PDF](mathstat/mathstat-LLI.pdf){.btn .btn-primary role="button"}
[Canvas](https://canvas.usask.ca/){.btn .btn-primary role="button"}

## Course Syllabus

[2026 Winter](syllabus2026.html){.btn .btn-primary role="button"}
[2027 Winter](syllabus2027.html){.btn .btn-primary role="button"}