- name: Inject Commit Dates into HTML
        run: |
          echo "Starting commit date injection..."
          # Find HTML files (adjust path if they aren't in the root)
          find . -name "*.html" -type f | while read -r html_file; do
            echo "Processing $html_file"
            # Get the ISO 8601 commit date for the file
            commit_date_iso=$(git log -1 --format=%cI --follow -- "$html_file")

            if [ -z "$commit_date_iso" ]; then
              echo "  WARNING: Could not find commit date for $html_file. Using placeholder."
              formatted_date="N/A"
              # Use explicit backup suffix ".bak" for sed -i for better compatibility
              sed -i.bak "s||Last modified: $formatted_date|g" "$html_file" && rm "${html_file}.bak" || echo "  SED command failed for N/A date in $html_file"
            else
              # Format the date to DD/MM/YYYY (Linux runner syntax)
              formatted_date=$(date -d "$commit_date_iso" +'%d/%m/%Y')
              echo "  Commit date: $commit_date_iso -> Formatted: $formatted_date"

              # Replace placeholder comment with the formatted date string
              # Ensure the placeholder exactly matches "" in your HTML
              # Use explicit backup suffix ".bak" for sed -i for better compatibility
              sed -i.bak "s||Last modified: $formatted_date|g" "$html_file" && rm "${html_file}.bak" || echo "  SED command failed for valid date in $html_file"
              
              # Check exit status of sed (optional, but good for debugging)
              if [ $? -ne 0 ]; then
                  echo "  ERROR: sed command failed for $html_file"
                  # Optionally exit the script if one file fails: exit 1 
              else
                  echo "  Injected date into $html_file"
              fi
            fi
          done
          echo "Finished commit date injection."
        shell: bash